import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { ALL_PERMISSIONS } from "./rbac.ts";
import {
  fillRoleGrantedMap,
  planStaffPermissionWrites,
  staffPermissionMutationErrorMessage,
} from "./staff-permission-toggles.ts";

function roleAllOn(): Map<string, boolean> {
  return new Map(ALL_PERMISSIONS.map((p) => [p, true]));
}

describe("fillRoleGrantedMap", () => {
  it("uses DEFAULT_MATRIX when a key was never seeded", () => {
    const map = fillRoleGrantedMap("employee", []);
    assert.equal(map.get("view_own_timesheets"), true);
    assert.equal(map.get("invite_staff"), false);
  });

  it("honors a seeded deny over DEFAULT_MATRIX", () => {
    const map = fillRoleGrantedMap("employee", [
      { permission: "view_own_timesheets", enabled: false },
    ]);
    assert.equal(map.get("view_own_timesheets"), false);
  });
});

describe("planStaffPermissionWrites", () => {
  it("writes one deny override when a single Owner toggle is flipped off", () => {
    const plan = planStaffPermissionWrites({
      toggles: ALL_PERMISSIONS.map((permission) => ({
        permission,
        granted: permission !== "invite_staff",
      })),
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(plan.deletes, []);
    assert.equal(plan.upserts.length, 1);
    assert.deepEqual(plan.upserts[0], {
      permission: "invite_staff",
      granted: false,
      previousValue: null,
      changeType: "individual_override_denied",
    });
  });

  it("removes the override when the toggle is returned to the role default", () => {
    const plan = planStaffPermissionWrites({
      toggles: [{ permission: "invite_staff", granted: true }],
      roleGranted: roleAllOn(),
      existingGranted: new Map([["invite_staff", false]]),
    });
    assert.deepEqual(plan.upserts, []);
    assert.deepEqual(plan.deletes, [{ permission: "invite_staff", previousValue: false }]);
  });

  it("skips no-ops so a full ALL_PERMISSIONS payload is not 80 writes", () => {
    const plan = planStaffPermissionWrites({
      toggles: ALL_PERMISSIONS.map((permission) => ({ permission, granted: true })),
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(plan, { upserts: [], deletes: [] });
  });

  it("does not rewrite an override that already matches the requested grant", () => {
    const plan = planStaffPermissionWrites({
      toggles: [{ permission: "invite_staff", granted: false }],
      roleGranted: roleAllOn(),
      existingGranted: new Map([["invite_staff", false]]),
    });
    assert.deepEqual(plan, { upserts: [], deletes: [] });
  });

  it("last toggle for a permission wins", () => {
    const plan = planStaffPermissionWrites({
      toggles: [
        { permission: "invite_staff", granted: false },
        { permission: "invite_staff", granted: true },
      ],
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(plan, { upserts: [], deletes: [] });
  });

  it("can mix a grant upsert and a matching-role delete", () => {
    const plan = planStaffPermissionWrites({
      toggles: [
        { permission: "invite_staff", granted: false },
        { permission: "view_clients", granted: true },
      ],
      roleGranted: new Map([
        ["invite_staff", true],
        ["view_clients", true],
      ]),
      existingGranted: new Map([["view_clients", false]]),
    });
    assert.equal(plan.upserts.length, 1);
    assert.equal(plan.upserts[0]?.permission, "invite_staff");
    assert.deepEqual(plan.deletes, [{ permission: "view_clients", previousValue: false }]);
  });
});

describe("staffPermissionMutationErrorMessage", () => {
  it("keeps a short app error", () => {
    assert.equal(
      staffPermissionMutationErrorMessage(
        new Error("Staffer not found in this organization"),
        "fallback",
      ),
      "Staffer not found in this organization",
    );
  });

  it("does not toast CloudFront HTML or gateway status text", () => {
    const html = `<!DOCTYPE html><html><body>ERROR: The request could not be satisfied. Generated by cloudfront (504)</body></html>`;
    assert.equal(
      staffPermissionMutationErrorMessage(new Error(html), "Could not save permissions"),
      "Could not save permissions",
    );
    assert.equal(
      staffPermissionMutationErrorMessage(
        new Error("504 Gateway Timeout"),
        "Could not save permissions",
      ),
      "Could not save permissions",
    );
  });

  it("uses the fallback for empty or oversized messages", () => {
    assert.equal(
      staffPermissionMutationErrorMessage(null, "Could not reset permissions"),
      "Could not reset permissions",
    );
    assert.equal(
      staffPermissionMutationErrorMessage(new Error("x".repeat(300)), "Could not save permissions"),
      "Could not save permissions",
    );
  });
});

describe("saveStaffPermissionToggles is batched", () => {
  it("does not loop every toggle with a per-row select/write", () => {
    const src = readFileSync(new URL("./permissions.functions.ts", import.meta.url), "utf8");
    const saveStart = src.indexOf("export const saveStaffPermissionToggles");
    const resetStart = src.indexOf("export const resetStaffPermissionOverrides");
    assert.ok(saveStart >= 0 && resetStart > saveStart);
    const saveBody = src.slice(saveStart, resetStart);
    assert.match(saveBody, /planStaffPermissionWrites/);
    assert.doesNotMatch(saveBody, /for \(const toggle of data\.toggles\)/);
  });
});
