/**
 * Diff staff permission toggles against role defaults + existing overrides.
 * The employee-profile Save used to loop every permission with a SELECT +
 * write + audit insert. That is ~80 sequential Supabase roundtrips from the
 * CloudFront/Lambda origin and is what wrapped as an opaque CloudFront HTML
 * 504. This planner is the only write plan; the server fn batches it.
 */

import { ALL_PERMISSIONS, defaultCan, type Permission, type Role } from "./rbac.ts";

export type StaffPermissionToggle = {
  permission: string;
  granted: boolean;
};

export type PlannedOverrideUpsert = {
  permission: string;
  granted: boolean;
  previousValue: boolean | null;
  changeType: "individual_override_granted" | "individual_override_denied";
};

export type PlannedOverrideDelete = {
  permission: string;
  previousValue: boolean | null;
};

export type StaffPermissionWritePlan = {
  upserts: PlannedOverrideUpsert[];
  deletes: PlannedOverrideDelete[];
};

/** role_permissions row if seeded, else DEFAULT_MATRIX. */
export function fillRoleGrantedMap(
  role: Role | null | undefined,
  rows: readonly { permission: string; enabled: boolean }[],
): Map<string, boolean> {
  const fromDb = new Map(rows.map((r) => [r.permission, !!r.enabled]));
  const out = new Map<string, boolean>();
  for (const perm of ALL_PERMISSIONS) {
    if (fromDb.has(perm)) out.set(perm, !!fromDb.get(perm));
    else out.set(perm, defaultCan(role, perm as Permission));
  }
  return out;
}

export function planStaffPermissionWrites(opts: {
  toggles: readonly StaffPermissionToggle[];
  roleGranted: ReadonlyMap<string, boolean>;
  existingGranted: ReadonlyMap<string, boolean>;
}): StaffPermissionWritePlan {
  const lastByPerm = new Map<string, boolean>();
  for (const toggle of opts.toggles) {
    lastByPerm.set(toggle.permission, toggle.granted);
  }

  const upserts: PlannedOverrideUpsert[] = [];
  const deletes: PlannedOverrideDelete[] = [];

  for (const [permission, granted] of lastByPerm) {
    const matchesRole = (opts.roleGranted.get(permission) ?? false) === granted;
    const hasExisting = opts.existingGranted.has(permission);
    const existing = hasExisting ? !!opts.existingGranted.get(permission) : undefined;

    if (matchesRole) {
      if (!hasExisting) continue;
      deletes.push({ permission, previousValue: existing ?? null });
      continue;
    }

    if (hasExisting && existing === granted) continue;
    upserts.push({
      permission,
      granted,
      previousValue: hasExisting ? (existing ?? null) : null,
      changeType: granted ? "individual_override_granted" : "individual_override_denied",
    });
  }

  return { upserts, deletes };
}

const GATEWAY_NOISE =
  /cloudfront|gateway timeout|timed out|504|502|503|403|request blocked|request could not be satisfied|generated by cloudfront|<!doctype|<html[\s>]|the request could not be satisfied|too much traffic|configuration error/i;

const LAST_RESORT_ERROR = "Could not complete that request. Please try again.";

function extractErrorText(error: unknown): string {
  if (typeof error === "string") return error;
  if (error instanceof Error) {
    const parts = [error.message];
    if (error.cause instanceof Error) parts.push(error.cause.message);
    else if (typeof error.cause === "string") parts.push(error.cause);
    return parts.filter(Boolean).join(" ");
  }
  if (error && typeof error === "object" && "message" in error) {
    const message = (error as { message?: unknown }).message;
    if (typeof message === "string") return message;
  }
  return "";
}

function isSafeUserMessage(text: string): boolean {
  const trimmed = text.replace(/\s+/g, " ").trim();
  if (!trimmed || trimmed.length > 240) return false;
  return !GATEWAY_NOISE.test(trimmed);
}

/**
 * Map server-fn / gateway failures to short UI copy.
 * Never return CloudFront / WAF HTML, even if the caller passed it as fallback
 * (the Profile Save toast did that and painted the 403 page over the form).
 */
export function staffPermissionMutationErrorMessage(error: unknown, fallback: string): string {
  const raw = extractErrorText(error).replace(/\s+/g, " ").trim();
  const safeFallback = isSafeUserMessage(fallback)
    ? fallback.replace(/\s+/g, " ").trim()
    : LAST_RESORT_ERROR;
  if (!raw) return safeFallback;
  if (!isSafeUserMessage(raw)) return safeFallback;
  return raw;
}

/** Individual overrides only — role-default grants are not existing rows. */
export function existingOverridesFromEffective(
  resolved: Record<string, { granted?: boolean; source?: string } | undefined> | null | undefined,
): Map<string, boolean> {
  const out = new Map<string, boolean>();
  if (!resolved) return out;
  for (const perm of ALL_PERMISSIONS) {
    const entry = resolved[perm];
    if (entry?.source === "individual_grant" || entry?.source === "individual_deny") {
      out.set(perm, !!entry.granted);
    }
  }
  return out;
}

/**
 * Toggles that actually change overrides. Profile Save must POST only these —
 * sending ALL_PERMISSIONS (~83 keys) is a same-origin CloudFront/WAF body.
 */
export function staffPermissionSaveToggles(opts: {
  draft: Record<string, boolean>;
  roleGranted: ReadonlyMap<string, boolean>;
  existingGranted: ReadonlyMap<string, boolean>;
}): StaffPermissionToggle[] {
  const plan = planStaffPermissionWrites({
    toggles: ALL_PERMISSIONS.map((permission) => ({
      permission,
      granted: !!opts.draft[permission],
    })),
    roleGranted: opts.roleGranted,
    existingGranted: opts.existingGranted,
  });
  return [
    ...plan.upserts.map((u) => ({ permission: u.permission, granted: u.granted })),
    ...plan.deletes.map((d) => ({
      permission: d.permission,
      granted: opts.roleGranted.get(d.permission) ?? false,
    })),
  ];
}
