/**
 * Diff staff permission toggles against role defaults + existing overrides.
 * The employee-profile Save used to loop every permission with a SELECT +
 * write + audit insert. That is ~80 sequential Supabase roundtrips from the
 * CloudFront/Lambda origin and is what wrapped as an opaque CloudFront HTML
 * 504. This planner is the only write plan; the server fn batches it.
 */

import { ALL_PERMISSIONS, defaultCan, type Permission, type Role } from "./rbac.ts";

export type StaffPermissionToggle = {
  permission: string;
  granted: boolean;
};

export type PlannedOverrideUpsert = {
  permission: string;
  granted: boolean;
  previousValue: boolean | null;
  changeType: "individual_override_granted" | "individual_override_denied";
};

export type PlannedOverrideDelete = {
  permission: string;
  previousValue: boolean | null;
};

export type StaffPermissionWritePlan = {
  upserts: PlannedOverrideUpsert[];
  deletes: PlannedOverrideDelete[];
};

/** role_permissions row if seeded, else DEFAULT_MATRIX. */
export function fillRoleGrantedMap(
  role: Role | null | undefined,
  rows: readonly { permission: string; enabled: boolean }[],
): Map<string, boolean> {
  const fromDb = new Map(rows.map((r) => [r.permission, !!r.enabled]));
  const out = new Map<string, boolean>();
  for (const perm of ALL_PERMISSIONS) {
    if (fromDb.has(perm)) out.set(perm, !!fromDb.get(perm));
    else out.set(perm, defaultCan(role, perm as Permission));
  }
  return out;
}

export function planStaffPermissionWrites(opts: {
  toggles: readonly StaffPermissionToggle[];
  roleGranted: ReadonlyMap<string, boolean>;
  existingGranted: ReadonlyMap<string, boolean>;
}): StaffPermissionWritePlan {
  const lastByPerm = new Map<string, boolean>();
  for (const toggle of opts.toggles) {
    lastByPerm.set(toggle.permission, toggle.granted);
  }

  const upserts: PlannedOverrideUpsert[] = [];
  const deletes: PlannedOverrideDelete[] = [];

  for (const [permission, granted] of lastByPerm) {
    const matchesRole = (opts.roleGranted.get(permission) ?? false) === granted;
    const hasExisting = opts.existingGranted.has(permission);
    const existing = hasExisting ? !!opts.existingGranted.get(permission) : undefined;

    if (matchesRole) {
      if (!hasExisting) continue;
      deletes.push({ permission, previousValue: existing ?? null });
      continue;
    }

    if (hasExisting && existing === granted) continue;
    upserts.push({
      permission,
      granted,
      previousValue: hasExisting ? (existing ?? null) : null,
      changeType: granted ? "individual_override_granted" : "individual_override_denied",
    });
  }

  return { upserts, deletes };
}

const GATEWAY_NOISE =
  /cloudfront|gateway timeout|timed out|504|502|503|request could not be satisfied|generated by cloudfront|<!doctype|<html[\s>]|the request could not be satisfied/i;

/** Map server-fn / gateway failures to a short toast. Never dump CloudFront HTML. */
export function staffPermissionMutationErrorMessage(error: unknown, fallback: string): string {
  const raw = error instanceof Error ? error.message : typeof error === "string" ? error : "";
  const trimmed = raw.replace(/\s+/g, " ").trim();
  if (!trimmed) return fallback;
  if (GATEWAY_NOISE.test(trimmed) || trimmed.length > 240) return fallback;
  return trimmed;
}
