import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { ALL_PERMISSIONS } from "./rbac.ts";
import {
  existingOverridesFromEffective,
  fillRoleGrantedMap,
  planStaffPermissionWrites,
  staffPermissionMutationErrorMessage,
  staffPermissionSaveToggles,
} from "./staff-permission-toggles.ts";

function roleAllOn(): Map<string, boolean> {
  return new Map(ALL_PERMISSIONS.map((p) => [p, true]));
}

describe("fillRoleGrantedMap", () => {
  it("uses DEFAULT_MATRIX when a key was never seeded", () => {
    const map = fillRoleGrantedMap("employee", []);
    assert.equal(map.get("view_own_timesheets"), true);
    assert.equal(map.get("invite_staff"), false);
  });

  it("honors a seeded deny over DEFAULT_MATRIX", () => {
    const map = fillRoleGrantedMap("employee", [
      { permission: "view_own_timesheets", enabled: false },
    ]);
    assert.equal(map.get("view_own_timesheets"), false);
  });
});

describe("planStaffPermissionWrites", () => {
  it("writes one deny override when a single Owner toggle is flipped off", () => {
    const plan = planStaffPermissionWrites({
      toggles: ALL_PERMISSIONS.map((permission) => ({
        permission,
        granted: permission !== "invite_staff",
      })),
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(plan.deletes, []);
    assert.equal(plan.upserts.length, 1);
    assert.deepEqual(plan.upserts[0], {
      permission: "invite_staff",
      granted: false,
      previousValue: null,
      changeType: "individual_override_denied",
    });
  });

  it("removes the override when the toggle is returned to the role default", () => {
    const plan = planStaffPermissionWrites({
      toggles: [{ permission: "invite_staff", granted: true }],
      roleGranted: roleAllOn(),
      existingGranted: new Map([["invite_staff", false]]),
    });
    assert.deepEqual(plan.upserts, []);
    assert.deepEqual(plan.deletes, [{ permission: "invite_staff", previousValue: false }]);
  });

  it("skips no-ops so a full ALL_PERMISSIONS payload is not 80 writes", () => {
    const plan = planStaffPermissionWrites({
      toggles: ALL_PERMISSIONS.map((permission) => ({ permission, granted: true })),
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(plan, { upserts: [], deletes: [] });
  });

  it("does not rewrite an override that already matches the requested grant", () => {
    const plan = planStaffPermissionWrites({
      toggles: [{ permission: "invite_staff", granted: false }],
      roleGranted: roleAllOn(),
      existingGranted: new Map([["invite_staff", false]]),
    });
    assert.deepEqual(plan, { upserts: [], deletes: [] });
  });

  it("last toggle for a permission wins", () => {
    const plan = planStaffPermissionWrites({
      toggles: [
        { permission: "invite_staff", granted: false },
        { permission: "invite_staff", granted: true },
      ],
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(plan, { upserts: [], deletes: [] });
  });

  it("can mix a grant upsert and a matching-role delete", () => {
    const plan = planStaffPermissionWrites({
      toggles: [
        { permission: "invite_staff", granted: false },
        { permission: "view_clients", granted: true },
      ],
      roleGranted: new Map([
        ["invite_staff", true],
        ["view_clients", true],
      ]),
      existingGranted: new Map([["view_clients", false]]),
    });
    assert.equal(plan.upserts.length, 1);
    assert.equal(plan.upserts[0]?.permission, "invite_staff");
    assert.deepEqual(plan.deletes, [{ permission: "view_clients", previousValue: false }]);
  });
});

describe("staffPermissionMutationErrorMessage", () => {
  it("keeps a short app error", () => {
    assert.equal(
      staffPermissionMutationErrorMessage(
        new Error("Staffer not found in this organization"),
        "fallback",
      ),
      "Staffer not found in this organization",
    );
  });

  it("does not toast CloudFront HTML or gateway status text", () => {
    const html = `<!DOCTYPE html><html><body>ERROR: The request could not be satisfied. Generated by cloudfront (504)</body></html>`;
    assert.equal(
      staffPermissionMutationErrorMessage(new Error(html), "Could not save permissions"),
      "Could not save permissions",
    );
    assert.equal(
      staffPermissionMutationErrorMessage(
        new Error("504 Gateway Timeout"),
        "Could not save permissions",
      ),
      "Could not save permissions",
    );
  });

  it("never returns CloudFront 403 HTML even when fallback is the same HTML", () => {
    const html = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><title>ERROR</title></head><body><h1>403 ERROR</h1><h2>Request blocked</h2><p>Generated by cloudfront (CloudFront)</p></body></html>`;
    assert.equal(
      staffPermissionMutationErrorMessage(new Error(html), html),
      "Could not complete that request. Please try again.",
    );
    assert.equal(
      staffPermissionMutationErrorMessage(new Error("403 ERROR Request blocked"), html),
      "Could not complete that request. Please try again.",
    );
  });

  it("uses the fallback for empty or oversized messages", () => {
    assert.equal(
      staffPermissionMutationErrorMessage(null, "Could not reset permissions"),
      "Could not reset permissions",
    );
    assert.equal(
      staffPermissionMutationErrorMessage(new Error("x".repeat(300)), "Could not save permissions"),
      "Could not save permissions",
    );
  });
});

describe("staffPermissionSaveToggles", () => {
  it("sends nothing when the draft matches role defaults and there are no overrides", () => {
    const toggles = staffPermissionSaveToggles({
      draft: Object.fromEntries(ALL_PERMISSIONS.map((p) => [p, true])),
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(toggles, []);
  });

  it("sends only the flipped override, not the full ALL_PERMISSIONS body", () => {
    const draft = Object.fromEntries(ALL_PERMISSIONS.map((p) => [p, true]));
    draft.invite_staff = false;
    const toggles = staffPermissionSaveToggles({
      draft,
      roleGranted: roleAllOn(),
      existingGranted: new Map(),
    });
    assert.deepEqual(toggles, [{ permission: "invite_staff", granted: false }]);
    const body = JSON.stringify({
      data: {
        organizationId: "00000000-0000-0000-0000-000000000001",
        targetUserId: "00000000-0000-0000-0000-000000000002",
        toggles,
      },
    });
    assert.ok(body.length < 400);
  });

  it("reads only individual overrides from effective permissions", () => {
    const existing = existingOverridesFromEffective({
      invite_staff: { granted: false, source: "individual_deny" },
      view_clients: { granted: true, source: "role" },
    });
    assert.deepEqual([...existing.entries()], [["invite_staff", false]]);
  });
});

describe("saveStaffPermissionToggles is batched", () => {
  it("does not loop every toggle with a per-row select/write", () => {
    const src = readFileSync(new URL("./permissions.functions.ts", import.meta.url), "utf8");
    const saveStart = src.indexOf("export const saveStaffPermissionToggles");
    const resetStart = src.indexOf("export const resetStaffPermissionOverrides");
    assert.ok(saveStart >= 0 && resetStart > saveStart);
    const saveBody = src.slice(saveStart, resetStart);
    assert.match(saveBody, /planStaffPermissionWrites/);
    assert.doesNotMatch(saveBody, /for \(const toggle of data\.toggles\)/);
  });
});

describe("employee Profile Save does not POST every permission or dump CDN HTML", () => {
  it("plans dirty toggles and uses a short safe fallback", () => {
    const panel = readFileSync(
      new URL("../components/employees/staff-profile-panel.tsx", import.meta.url),
      "utf8",
    );
    assert.match(panel, /staffPermissionSaveToggles/);
    assert.match(panel, /existingOverridesFromEffective/);
    assert.match(panel, /Could not save/);
    assert.doesNotMatch(panel, /ALL_PERMISSIONS\.map\(\(permission\) => \(\{/);
    assert.doesNotMatch(panel, /staffPermissionMutationErrorMessage\(e,\s*\(e as Error\)\.message/);
  });
});
