// Standing / previously-unseeded DHHS91172 duties. Inserted idempotently
// the first time an org opens the compliance register (and via SQL handoff
// for TNS). Titles must match sow-obligation-catalog.ts and DSPD_AUDIT_ITEMS.

export type StandingDutySeed = {
  title: string;
  description: string;
  source_policy_section: string;
  cadence: "weekly" | "monthly" | "quarterly" | "annually" | "per_event" | "one_time";
  due_day_config: Record<string, unknown>;
  reminder_days_before: number[];
  evidence_type: "attestation" | "upload" | "upload_and_attestation" | "form";
  attestation_text: string | null;
  requires_individual_completion: boolean;
  assignee_role: "any_assigned" | "managers_only" | "admin_only";
  scope: "org" | "staff" | "staff_per_client";
  target_service_codes: string[];
  /** When true, assigned_to_groups is set to the All Staff auto-group. */
  assign_all_staff: boolean;
};

export const STANDING_SOW_DUTIES: StandingDutySeed[] = [
  {
    title: "Emergency Management and Business Continuity Plan",
    description:
      "Keep a current Emergency Management and Business Continuity Plan on file (CST 46). This is a standing capability, not a recurring class.",
    source_policy_section: "CST 46",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Annual Emergency Management Plan Training",
    description:
      "Staff are trained at least annually on the Contractor's Emergency Management and Business Continuity Plan (CST 46). Separate from the 30-day orientation.",
    source_policy_section: "CST 46",
    cadence: "annually",
    due_day_config: { anniversary_based: true, start_year: 1 },
    reminder_days_before: [30, 14],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that I have completed annual training on this organization's Emergency Management and Business Continuity Plan.",
    requires_individual_completion: true,
    assignee_role: "any_assigned",
    scope: "staff",
    target_service_codes: [],
    assign_all_staff: true,
  },
  {
    title: "Staff Conflict of Interest Process",
    description:
      "A written process for addressing staff conflict of interest (CST 9 & 10). Policy on file; not a per-period upload unless the policy changes.",
    source_policy_section: "CST 9 & 10",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Person Discharge Process",
    description:
      "Written discharge procedure for when a Person leaves services (SOW §1.22(c)). Triggered by a discharge, not a calendar.",
    source_policy_section: "SOW Article 1.22 (c)",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Internal Quality Management Plan",
    description:
      "Internal Quality Management Plan is followed and can be externally validated (CST 50).",
    source_policy_section: "CST 50",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "General, Professional, and Automobile Liability Insurance",
    description:
      "Current General, Professional, and Automobile liability insurance at contracted minimums (CST 29–36). Track expiration on the declarations page.",
    source_policy_section: "CST 29–36",
    cadence: "annually",
    due_day_config: { month: 7, day_of_month: 1 },
    reminder_days_before: [60, 30, 14],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "DHHS Code of Conduct — Signed",
    description:
      "Staff assigned to SLN, SLH, HHS, or PPS have a signed DHHS Code of Conduct on file (CST 76).",
    source_policy_section: "CST 76",
    cadence: "one_time",
    due_day_config: { days_after_hire: 30 },
    reminder_days_before: [14, 7],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: true,
    assignee_role: "any_assigned",
    scope: "staff",
    target_service_codes: ["SLN", "SLH", "HHS", "PPS"],
    assign_all_staff: true,
  },
  {
    title: "ABI Training — Before Working Alone",
    description:
      "Staff serving Persons with acquired brain injury complete ABI training before working alone (behavior effects, hospital-to-community transition, functional impact, health/medication, staff role, family perspective). SOW §1.8.",
    source_policy_section: "SOW Article 1.8 (ABI training)",
    cadence: "one_time",
    due_day_config: { days_after_hire: 0 },
    reminder_days_before: [14, 7, 3],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that I have completed ABI training covering behavior effects, hospital-to-community transition, functional impact, health and medication, the staff role, and family perspective, and that I will not work alone with a Person with ABI until this is on file.",
    requires_individual_completion: true,
    assignee_role: "any_assigned",
    scope: "staff",
    target_service_codes: [],
    assign_all_staff: true,
  },
  {
    title: "DHHS Medicaid 101 Training — Contractor",
    description:
      "Contractor-level DHHS Medicaid 101 within 30 days of a fully executed contract and annually thereafter (SOW §1.7(1)). Separate from the staff orientation Medicaid 101 topic.",
    source_policy_section: "SOW Article 1.7 (1)",
    cadence: "annually",
    due_day_config: { month: 7, day_of_month: 31 },
    reminder_days_before: [30, 14],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that this contractor completed DHHS Medicaid 101 for the current contract year and that applicable portions have been trained to staff.",
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Utah Medicaid Provider Manuals — Annual Memo",
    description:
      "Read Utah Medicaid provider manuals and rules within 90 days of contract execution and annually thereafter; file a memo (SOW §1.7(2)). Same review covers DSPD R539 and DHHS rules (§1.7(3)–(4)).",
    source_policy_section: "SOW Article 1.7 (2)–(4)",
    cadence: "annually",
    due_day_config: { month: 9, day_of_month: 28 },
    reminder_days_before: [30, 14],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that this contractor has read and is familiar with the Utah Medicaid provider manuals, Medicaid rules, DSPD R539, and applicable DHHS rules, and that the required memo is on file.",
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Volunteer Training File — When Volunteers Are Used",
    description:
      "When regularly scheduled volunteers are used, keep written training covering SOW §1.6(3) topics. Friends and natural supports the Person chooses are not volunteers.",
    source_policy_section: "SOW Article 1.6",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "USTEPS and UPI Contractor Accounts",
    description:
      "Keep current USTEPS and UPI accounts plus DSPD forms 0-9 (company designee) and 0-8 (at least one individual user) (SOW §1.4(2), §1.15).",
    source_policy_section: "SOW Article 1.4 (2) / 1.15",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that this contractor has a current USTEPS and UPI account and that the 0-9 company designee and at least one 0-8 individual user form are on file.",
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Medicaid Provider Enrollment — Current",
    description:
      "Stay enrolled as a Medicaid provider for the Community Support, Community Transition, and ABI waivers (SOW §1.4(1), §1.13).",
    source_policy_section: "SOW Article 1.4 (1) / 1.13",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Medicaid Provider Change Notifications",
    description:
      "Notify DSPD of contact changes within 7 calendar days and ownership / legal name / EIN changes within 30 calendar days (SOW §1.13(2)–(3)). Produce Medicaid provider documents within 7 days of a written DSPD request.",
    source_policy_section: "SOW Article 1.13 (2)–(3)",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that no unreported Medicaid-provider change is outstanding, and that any notice required by SOW §1.13 has been sent on time.",
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "No Gifts or Purchases-from-Staff Process",
    description:
      "Written process that contractor and staff do not accept money from a Person and do not let a Person make purchases from the contractor or staff (SOW §1.28(9)–(10)).",
    source_policy_section: "SOW Article 1.28 (9) & (10)",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Governing or Policy-Making Board Records",
    description:
      "If the contractor has a governing or policy-making board: keep by-laws, meet at least quarterly, and keep minutes (SOW §1.14).",
    source_policy_section: "SOW Article 1.14",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Personnel Policies and Job Descriptions",
    description:
      "Written personnel policies and a job description for each staff position (SOW §1.17).",
    source_policy_section: "SOW Article 1.17",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Operating Policies and Procedures",
    description:
      "Written operating policies covering staff/supervisory responsibilities, transportation, grievances, and emergency procedures (SOW §1.18).",
    source_policy_section: "SOW Article 1.18",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Human Rights Plan",
    description:
      "Written Human Rights Plan in compliance with the HCBS Settings Rule (SOW §1.21). Separate from the live HRC roster. Required unless the contractor only provides CHA, HSQ, or PBA.",
    source_policy_section: "SOW Article 1.21",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Health Support Policies and Procedures",
    description:
      "Written health-support policies for Persons' medical needs (SOW §1.23). Day-to-day medical records are Person artifacts.",
    source_policy_section: "SOW Article 1.23",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload",
    attestation_text: null,
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: [],
    assign_all_staff: false,
  },
  {
    title: "Housemate Informed-Choice Discussion",
    description:
      "For HHS, PPS, or RHS: document an informed discussion about housemates and household accommodations at placement and any change on or after July 1, 2026 (SOW §1.35).",
    source_policy_section: "SOW Article 1.35",
    cadence: "per_event",
    due_day_config: {},
    reminder_days_before: [],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that each Person receiving residential services has a written informed-choice housemate discussion on file, updated when a housemate changes.",
    requires_individual_completion: false,
    assignee_role: "managers_only",
    scope: "org",
    target_service_codes: ["HHS", "PPS", "RHS"],
    assign_all_staff: false,
  },
  {
    title: "DSI Annual Outcome Report — Google Form Submission",
    description:
      "Fiscal-year Day Supports outcome report via the DSPD Google Form by August 30 (SOW §8.6).",
    source_policy_section: "SOW Article 8.6",
    cadence: "annually",
    due_day_config: { month: 8, day_of_month: 30 },
    reminder_days_before: [30, 14],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that the DSI / Day Supports fiscal-year outcome report was submitted on the DSPD Google Form for this reporting year.",
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: ["DSI"],
    assign_all_staff: false,
  },
  {
    title: "SEI Annual Outcome Report — Google Form Submission",
    description:
      "Fiscal-year SEI outcome report via the DSPD Google Form by August 30 (SOW §30.7).",
    source_policy_section: "SOW Article 30.7",
    cadence: "annually",
    due_day_config: { month: 8, day_of_month: 30 },
    reminder_days_before: [30, 14],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that the SEI fiscal-year outcome report was submitted on the DSPD Google Form for this reporting year.",
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: ["SEI"],
    assign_all_staff: false,
  },
  {
    title: "Supported Living Annual Outcome Report — Google Form Submission",
    description:
      "Fiscal-year Supported Living (SLH/SLN) outcome report via the DSPD Google Form by August 30 (SOW §31.5 / §32.7).",
    source_policy_section: "SOW Article 31.5 / 32.7",
    cadence: "annually",
    due_day_config: { month: 8, day_of_month: 30 },
    reminder_days_before: [30, 14],
    evidence_type: "upload_and_attestation",
    attestation_text:
      "I attest that the Supported Living fiscal-year outcome report was submitted on the DSPD Google Form for this reporting year.",
    requires_individual_completion: false,
    assignee_role: "admin_only",
    scope: "org",
    target_service_codes: ["SLH", "SLN"],
    assign_all_staff: false,
  },
  {
    title: "Person-Centered Thinking — [Client Name]",
    description:
      "Each assigned staff member completes the person-centered thinking form for that client within 30 days of assignment. This is the per-client form — separate from the hire-level Person-Centered Thinking and Practices course.",
    source_policy_section: "SOW §1.8(5)(C) — Person-Centered Thinking (per client)",
    cadence: "one_time",
    due_day_config: { days_after_assignment: 30 },
    reminder_days_before: [14, 7, 3],
    evidence_type: "form",
    attestation_text: null,
    requires_individual_completion: true,
    assignee_role: "any_assigned",
    scope: "staff_per_client",
    target_service_codes: [],
    assign_all_staff: false,
  },
];

export const STANDING_SOW_TITLES = new Set(STANDING_SOW_DUTIES.map((d) => d.title));
