project_id = "mmknqtdrefbzwfdtykza"

[functions.parse-receipt-ocr]
verify_jwt = true

[functions.format-training-content]
verify_jwt = true

[functions.parse-referral-doc]
verify_jwt = true

[functions.review-incident-report]
verify_jwt = true

