import { forwardRef, type ButtonHTMLAttributes, type HTMLAttributes, type ReactNode } from "react";
import { Hexagon, Sparkles, Loader2 } from "lucide-react";

/**
 * Single source of truth for the NECTAR visual signature.
 *
 * Brand tokens:
 *   navy surface  #141a3d  (--navy-800)
 *   navy deep     #0d112b  (--navy-900)
 *   amber accent  #f4a93a / #F2A23C  (--amber-500)
 *   amber-on-navy text  #f4a93a
 *   amber-pill text     #412402 (dark cocoa for AA on amber)
 *
 * Use these components anywhere NECTAR generates, summarizes,
 * suggests, or assists so the brand reads instantly.
 */

const cn = (...c: Array<string | false | null | undefined>) => c.filter(Boolean).join(" ");

/* -------------------------------------------------------------------------- */
/* NectarMark — circular hexagon+sparkle avatar (the "face" of NECTAR)        */
/* -------------------------------------------------------------------------- */

export function NectarMark({
  size = "md",
  className,
}: {
  size?: "sm" | "md" | "lg";
  className?: string;
}) {
  const dims = size === "sm" ? "h-7 w-7" : size === "lg" ? "h-16 w-16" : "h-10 w-10";
  const hex = size === "sm" ? "h-4 w-4" : size === "lg" ? "h-9 w-9" : "h-5 w-5";
  const spark = size === "sm" ? "h-2 w-2" : size === "lg" ? "h-3.5 w-3.5" : "h-2.5 w-2.5";
  return (
    <span
      aria-hidden
      className={cn(
        "relative inline-flex shrink-0 items-center justify-center rounded-full",
        "bg-[#0d112b] text-[#f4a93a] shadow-[0_4px_14px_-6px_rgba(13,17,43,0.6)] ring-1 ring-[#f4a93a]/30",
        dims,
        className,
      )}
    >
      <Hexagon className={cn(hex)} fill="currentColor" strokeWidth={1.25} />
      <span className="absolute -right-0.5 -top-0.5 inline-flex items-center justify-center rounded-full bg-[#f4a93a] p-[2px] text-[#412402] shadow-sm">
        <Sparkles className={spark} strokeWidth={2.5} />
      </span>
    </span>
  );
}

/* -------------------------------------------------------------------------- */
/* NectarBadge — pill wordmark "✨ NECTAR" on amber, the recognizable tag     */
/* -------------------------------------------------------------------------- */

export function NectarBadge({
  size = "md",
  live = false,
  label = "NECTAR",
  className,
}: {
  size?: "xs" | "sm" | "md";
  live?: boolean;
  label?: string;
  className?: string;
}) {
  const pad =
    size === "xs"
      ? "px-2 py-0.5 text-[9px]"
      : size === "sm"
      ? "px-2.5 py-1 text-[10px]"
      : "px-3 py-1 text-[11px]";
  const ic = size === "xs" ? "h-2.5 w-2.5" : "h-3 w-3";
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full bg-[image:var(--gradient-amber)]",
        "font-bold uppercase tracking-wider text-[#412402]",
        "shadow-[0_1px_0_rgba(255,255,255,0.35)_inset]",
        pad,
        className,
      )}
    >
      <Sparkles className={ic} strokeWidth={2.5} />
      <span>{label}</span>
      {live && (
        <span className="ml-1 inline-flex items-center gap-1 text-[#412402]/80">
          <span className="relative inline-flex h-1.5 w-1.5">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-[#1f7a4d] opacity-70" />
            <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-[#15a06a]" />
          </span>
          <span className="text-[9px] font-bold uppercase tracking-wider">live</span>
        </span>
      )}
    </span>
  );
}

/* -------------------------------------------------------------------------- */
/* NectarChip — subtle inline tag for "NECTAR-generated" annotations          */
/* -------------------------------------------------------------------------- */

export function NectarChip({
  children = "Generated by NECTAR",
  className,
}: {
  children?: ReactNode;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full border border-[#f4a93a]/40 bg-[#f4a93a]/10",
        "px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-[#7a4a0a]",
        className,
      )}
    >
      <Sparkles className="h-2.5 w-2.5" strokeWidth={2.5} />
      {children}
    </span>
  );
}

/* -------------------------------------------------------------------------- */
/* NectarSurface — the navy panel background NECTAR sections sit on           */
/* -------------------------------------------------------------------------- */

export const NectarSurface = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function NectarSurface({ className, children, ...rest }, ref) {
    return (
      <div
        ref={ref}
        {...rest}
        className={cn(
          "relative overflow-hidden rounded-2xl border border-[#1f2752] bg-[#141a3d] text-white",
          "shadow-[0_12px_30px_-20px_rgba(13,17,43,0.6)]",
          className,
        )}
      >
        {/* signature amber sparkle wash in the top-right */}
        <span
          aria-hidden
          className="pointer-events-none absolute -right-10 -top-10 h-40 w-40 rounded-full"
          style={{
            background:
              "radial-gradient(closest-side, rgba(244,169,58,0.18), transparent 70%)",
          }}
        />
        {children}
      </div>
    );
  },
);

/* -------------------------------------------------------------------------- */
/* NectarCard — light variant for in-flow cards (Billing alerts, etc.)        */
/* -------------------------------------------------------------------------- */

export function NectarCard({
  className,
  children,
  ...rest
}: HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      {...rest}
      className={cn(
        "relative overflow-hidden rounded-xl border border-[#f4a93a]/30 bg-card shadow-sm",
        "before:absolute before:inset-y-0 before:left-0 before:w-1 before:bg-[image:var(--gradient-amber)]",
        className,
      )}
    >
      {children}
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* NectarHeader — branded section header (mark + title + NECTAR badge)        */
/* -------------------------------------------------------------------------- */

export function NectarHeader({
  title,
  eyebrow,
  description,
  markSize = "md",
  surface = "navy",
  right,
  className,
}: {
  title: ReactNode;
  eyebrow?: ReactNode;
  description?: ReactNode;
  markSize?: "sm" | "md" | "lg";
  /** "navy" = dark NectarSurface header; "light" = light card header */
  surface?: "navy" | "light";
  right?: ReactNode;
  className?: string;
}) {
  if (surface === "navy") {
    return (
      <NectarSurface className={cn("p-5", className)}>
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <NectarMark size={markSize} />
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <NectarBadge size="xs" />
                {eyebrow && (
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-[#fed7aa]/90">
                    {eyebrow}
                  </span>
                )}
              </div>
              <h2 className="mt-1 font-display text-lg font-bold tracking-tight text-white">
                {title}
              </h2>
              {description && (
                <p className="mt-0.5 text-sm text-white/75">{description}</p>
              )}
            </div>
          </div>
          {right}
        </div>
      </NectarSurface>
    );
  }
  return (
    <div className={cn("flex flex-wrap items-center justify-between gap-3", className)}>
      <div className="flex items-center gap-3">
        <NectarMark size={markSize} />
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <NectarBadge size="xs" />
            {eyebrow && (
              <span className="text-[10px] font-semibold uppercase tracking-wider text-[#7a4a0a]">
                {eyebrow}
              </span>
            )}
          </div>
          <h2 className="mt-1 font-display text-lg font-semibold tracking-tight text-[#0f1b3d]">
            {title}
          </h2>
          {description && (
            <p className="mt-0.5 text-sm text-muted-foreground">{description}</p>
          )}
        </div>
      </div>
      {right}
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* NectarButton — the canonical "Ask NECTAR" / "Run with NECTAR" CTA          */
/* -------------------------------------------------------------------------- */

type NectarButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: "primary" | "amber" | "ghost";
  loading?: boolean;
  icon?: ReactNode;
};

export const NectarButton = forwardRef<HTMLButtonElement, NectarButtonProps>(
  function NectarButton(
    { variant = "primary", loading, icon, children, className, disabled, ...rest },
    ref,
  ) {
    const base =
      "inline-flex min-h-[40px] items-center justify-center gap-2 rounded-md px-4 py-2 text-sm font-medium shadow-sm transition disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f4a93a]/50 focus-visible:ring-offset-2";
    const styles =
      variant === "amber"
        ? "bg-[image:var(--gradient-amber)] text-[#412402] hover:brightness-[1.04]"
        : variant === "ghost"
        ? "border border-[#f4a93a]/40 bg-[#f4a93a]/10 text-[#7a4a0a] hover:bg-[#f4a93a]/20"
        : "bg-[#0f1b3d] text-white hover:bg-[#1a2a5a]";
    const leading = loading ? (
      <Loader2 className="h-4 w-4 animate-spin" />
    ) : (
      icon ?? <Sparkles className="h-4 w-4" strokeWidth={2.5} />
    );
    return (
      <button
        ref={ref}
        {...rest}
        disabled={disabled || loading}
        className={cn(base, styles, className)}
      >
        {leading}
        {children}
      </button>
    );
  },
);
