/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as DashboardTrainingRouteImport } from './routes/dashboard.training'
import { Route as DashboardTracksRouteImport } from './routes/dashboard.tracks'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSuperAdminRouteImport } from './routes/dashboard.super-admin'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRolesRouteImport } from './routes/dashboard.roles'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProgramsAdminRouteImport } from './routes/dashboard.programs-admin'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard.programs'
import { Route as DashboardPermissionsRouteImport } from './routes/dashboard.permissions'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard.invitations'
import { Route as DashboardExternalCertificationsRouteImport } from './routes/dashboard.external-certifications'
import { Route as DashboardEmployeesRouteImport } from './routes/dashboard.employees'
import { Route as DashboardCertificationsRouteImport } from './routes/dashboard.certifications'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard.courses.index'
import { Route as DashboardTracksTrackSlugRouteImport } from './routes/dashboard.tracks.$trackSlug'
import { Route as DashboardProgramsProgramIdRouteImport } from './routes/dashboard.programs.$programId'
import { Route as DashboardCoursesMindsmithRouteImport } from './routes/dashboard.courses.mindsmith'
import { Route as DashboardCoursesCourseIdRouteImport } from './routes/dashboard.courses.$courseId'
import { Route as DashboardCoursesCourseIdEditRouteImport } from './routes/dashboard.courses.$courseId.edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrainingRoute = DashboardTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracksRoute = DashboardTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperAdminRoute = DashboardSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsAdminRoute = DashboardProgramsAdminRouteImport.update({
  id: '/programs-admin',
  path: '/programs-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPermissionsRoute = DashboardPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExternalCertificationsRoute =
  DashboardExternalCertificationsRouteImport.update({
    id: '/external-certifications',
    path: '/external-certifications',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificationsRoute = DashboardCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracksTrackSlugRoute =
  DashboardTracksTrackSlugRouteImport.update({
    id: '/$trackSlug',
    path: '/$trackSlug',
    getParentRoute: () => DashboardTracksRoute,
  } as any)
const DashboardProgramsProgramIdRoute =
  DashboardProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => DashboardProgramsRoute,
  } as any)
const DashboardCoursesMindsmithRoute =
  DashboardCoursesMindsmithRouteImport.update({
    id: '/courses/mindsmith',
    path: '/courses/mindsmith',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesCourseIdRoute =
  DashboardCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesCourseIdEditRoute =
  DashboardCoursesCourseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/external-certifications': typeof DashboardExternalCertificationsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/programs-admin': typeof DashboardProgramsAdminRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/tracks': typeof DashboardTracksRouteWithChildren
  '/dashboard/training': typeof DashboardTrainingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRouteWithChildren
  '/dashboard/courses/mindsmith': typeof DashboardCoursesMindsmithRoute
  '/dashboard/programs/$programId': typeof DashboardProgramsProgramIdRoute
  '/dashboard/tracks/$trackSlug': typeof DashboardTracksTrackSlugRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/external-certifications': typeof DashboardExternalCertificationsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/programs-admin': typeof DashboardProgramsAdminRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/tracks': typeof DashboardTracksRouteWithChildren
  '/dashboard/training': typeof DashboardTrainingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRouteWithChildren
  '/dashboard/courses/mindsmith': typeof DashboardCoursesMindsmithRoute
  '/dashboard/programs/$programId': typeof DashboardProgramsProgramIdRoute
  '/dashboard/tracks/$trackSlug': typeof DashboardTracksTrackSlugRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/external-certifications': typeof DashboardExternalCertificationsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/programs-admin': typeof DashboardProgramsAdminRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/tracks': typeof DashboardTracksRouteWithChildren
  '/dashboard/training': typeof DashboardTrainingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRouteWithChildren
  '/dashboard/courses/mindsmith': typeof DashboardCoursesMindsmithRoute
  '/dashboard/programs/$programId': typeof DashboardProgramsProgramIdRoute
  '/dashboard/tracks/$trackSlug': typeof DashboardTracksTrackSlugRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/unauthorized'
    | '/certificate/$code'
    | '/dashboard/billing'
    | '/dashboard/certifications'
    | '/dashboard/employees'
    | '/dashboard/external-certifications'
    | '/dashboard/invitations'
    | '/dashboard/permissions'
    | '/dashboard/programs'
    | '/dashboard/programs-admin'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/super-admin'
    | '/dashboard/team'
    | '/dashboard/tracks'
    | '/dashboard/training'
    | '/verify/$code'
    | '/dashboard/'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/mindsmith'
    | '/dashboard/programs/$programId'
    | '/dashboard/tracks/$trackSlug'
    | '/dashboard/courses/'
    | '/dashboard/courses/$courseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/employee'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/unauthorized'
    | '/certificate/$code'
    | '/dashboard/billing'
    | '/dashboard/certifications'
    | '/dashboard/employees'
    | '/dashboard/external-certifications'
    | '/dashboard/invitations'
    | '/dashboard/permissions'
    | '/dashboard/programs'
    | '/dashboard/programs-admin'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/super-admin'
    | '/dashboard/team'
    | '/dashboard/tracks'
    | '/dashboard/training'
    | '/verify/$code'
    | '/dashboard'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/mindsmith'
    | '/dashboard/programs/$programId'
    | '/dashboard/tracks/$trackSlug'
    | '/dashboard/courses'
    | '/dashboard/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/unauthorized'
    | '/certificate/$code'
    | '/dashboard/billing'
    | '/dashboard/certifications'
    | '/dashboard/employees'
    | '/dashboard/external-certifications'
    | '/dashboard/invitations'
    | '/dashboard/permissions'
    | '/dashboard/programs'
    | '/dashboard/programs-admin'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/super-admin'
    | '/dashboard/team'
    | '/dashboard/tracks'
    | '/dashboard/training'
    | '/verify/$code'
    | '/dashboard/'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/mindsmith'
    | '/dashboard/programs/$programId'
    | '/dashboard/tracks/$trackSlug'
    | '/dashboard/courses/'
    | '/dashboard/courses/$courseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeeRoute: typeof EmployeeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/training': {
      id: '/dashboard/training'
      path: '/training'
      fullPath: '/dashboard/training'
      preLoaderRoute: typeof DashboardTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracks': {
      id: '/dashboard/tracks'
      path: '/tracks'
      fullPath: '/dashboard/tracks'
      preLoaderRoute: typeof DashboardTracksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/super-admin': {
      id: '/dashboard/super-admin'
      path: '/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof DashboardSuperAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs-admin': {
      id: '/dashboard/programs-admin'
      path: '/programs-admin'
      fullPath: '/dashboard/programs-admin'
      preLoaderRoute: typeof DashboardProgramsAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs': {
      id: '/dashboard/programs'
      path: '/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/permissions': {
      id: '/dashboard/permissions'
      path: '/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof DashboardPermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/external-certifications': {
      id: '/dashboard/external-certifications'
      path: '/external-certifications'
      fullPath: '/dashboard/external-certifications'
      preLoaderRoute: typeof DashboardExternalCertificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees': {
      id: '/dashboard/employees'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certifications': {
      id: '/dashboard/certifications'
      path: '/certifications'
      fullPath: '/dashboard/certifications'
      preLoaderRoute: typeof DashboardCertificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/courses'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracks/$trackSlug': {
      id: '/dashboard/tracks/$trackSlug'
      path: '/$trackSlug'
      fullPath: '/dashboard/tracks/$trackSlug'
      preLoaderRoute: typeof DashboardTracksTrackSlugRouteImport
      parentRoute: typeof DashboardTracksRoute
    }
    '/dashboard/programs/$programId': {
      id: '/dashboard/programs/$programId'
      path: '/$programId'
      fullPath: '/dashboard/programs/$programId'
      preLoaderRoute: typeof DashboardProgramsProgramIdRouteImport
      parentRoute: typeof DashboardProgramsRoute
    }
    '/dashboard/courses/mindsmith': {
      id: '/dashboard/courses/mindsmith'
      path: '/courses/mindsmith'
      fullPath: '/dashboard/courses/mindsmith'
      preLoaderRoute: typeof DashboardCoursesMindsmithRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$courseId': {
      id: '/dashboard/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/dashboard/courses/$courseId'
      preLoaderRoute: typeof DashboardCoursesCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$courseId/edit': {
      id: '/dashboard/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/dashboard/courses/$courseId/edit'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditRouteImport
      parentRoute: typeof DashboardCoursesCourseIdRoute
    }
  }
}

interface DashboardProgramsRouteChildren {
  DashboardProgramsProgramIdRoute: typeof DashboardProgramsProgramIdRoute
}

const DashboardProgramsRouteChildren: DashboardProgramsRouteChildren = {
  DashboardProgramsProgramIdRoute: DashboardProgramsProgramIdRoute,
}

const DashboardProgramsRouteWithChildren =
  DashboardProgramsRoute._addFileChildren(DashboardProgramsRouteChildren)

interface DashboardTracksRouteChildren {
  DashboardTracksTrackSlugRoute: typeof DashboardTracksTrackSlugRoute
}

const DashboardTracksRouteChildren: DashboardTracksRouteChildren = {
  DashboardTracksTrackSlugRoute: DashboardTracksTrackSlugRoute,
}

const DashboardTracksRouteWithChildren = DashboardTracksRoute._addFileChildren(
  DashboardTracksRouteChildren,
)

interface DashboardCoursesCourseIdRouteChildren {
  DashboardCoursesCourseIdEditRoute: typeof DashboardCoursesCourseIdEditRoute
}

const DashboardCoursesCourseIdRouteChildren: DashboardCoursesCourseIdRouteChildren =
  {
    DashboardCoursesCourseIdEditRoute: DashboardCoursesCourseIdEditRoute,
  }

const DashboardCoursesCourseIdRouteWithChildren =
  DashboardCoursesCourseIdRoute._addFileChildren(
    DashboardCoursesCourseIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCertificationsRoute: typeof DashboardCertificationsRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardExternalCertificationsRoute: typeof DashboardExternalCertificationsRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardPermissionsRoute: typeof DashboardPermissionsRoute
  DashboardProgramsRoute: typeof DashboardProgramsRouteWithChildren
  DashboardProgramsAdminRoute: typeof DashboardProgramsAdminRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuperAdminRoute: typeof DashboardSuperAdminRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTracksRoute: typeof DashboardTracksRouteWithChildren
  DashboardTrainingRoute: typeof DashboardTrainingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCoursesCourseIdRoute: typeof DashboardCoursesCourseIdRouteWithChildren
  DashboardCoursesMindsmithRoute: typeof DashboardCoursesMindsmithRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCertificationsRoute: DashboardCertificationsRoute,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardExternalCertificationsRoute: DashboardExternalCertificationsRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardPermissionsRoute: DashboardPermissionsRoute,
  DashboardProgramsRoute: DashboardProgramsRouteWithChildren,
  DashboardProgramsAdminRoute: DashboardProgramsAdminRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuperAdminRoute: DashboardSuperAdminRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTracksRoute: DashboardTracksRouteWithChildren,
  DashboardTrainingRoute: DashboardTrainingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCoursesCourseIdRoute: DashboardCoursesCourseIdRouteWithChildren,
  DashboardCoursesMindsmithRoute: DashboardCoursesMindsmithRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeeRoute: EmployeeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
