/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FixAdminRouteImport } from './routes/fix-admin'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as DashboardTracksRouteImport } from './routes/dashboard.tracks'
import { Route as DashboardTimeclockRouteImport } from './routes/dashboard.timeclock'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard.teams'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSuperAdminRouteImport } from './routes/dashboard.super-admin'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSchedulingRouteImport } from './routes/dashboard.scheduling'
import { Route as DashboardRolesRouteImport } from './routes/dashboard.roles'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardReimbursementsRouteImport } from './routes/dashboard.reimbursements'
import { Route as DashboardRecordsDeskRouteImport } from './routes/dashboard.records-desk'
import { Route as DashboardProgramsAdminRouteImport } from './routes/dashboard.programs-admin'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard.programs'
import { Route as DashboardPermissionsRouteImport } from './routes/dashboard.permissions'
import { Route as DashboardPbaLedgerRouteImport } from './routes/dashboard.pba-ledger'
import { Route as DashboardNectarDocsRouteImport } from './routes/dashboard.nectar-docs'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard.invitations'
import { Route as DashboardHostHomeControlRouteImport } from './routes/dashboard.host-home-control'
import { Route as DashboardHiveExecRouteImport } from './routes/dashboard.hive-exec'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardExternalCertificationsRouteImport } from './routes/dashboard.external-certifications'
import { Route as DashboardEmployeesRouteImport } from './routes/dashboard.employees'
import { Route as DashboardEmarRouteImport } from './routes/dashboard.emar'
import { Route as DashboardDailyLogsRouteImport } from './routes/dashboard.daily-logs'
import { Route as DashboardComplianceDeskRouteImport } from './routes/dashboard.compliance-desk'
import { Route as DashboardCommandCenterRouteImport } from './routes/dashboard.command-center'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardClientBillingCodesRouteImport } from './routes/dashboard.client-billing-codes'
import { Route as DashboardCertificationsRouteImport } from './routes/dashboard.certifications'
import { Route as DashboardBilling520RouteImport } from './routes/dashboard.billing-520'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as DashboardTrainingIndexRouteImport } from './routes/dashboard.training.index'
import { Route as DashboardHiveExecIndexRouteImport } from './routes/dashboard.hive-exec.index'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard.courses.index'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard.billing.index'
import { Route as DashboardWorkspaceClientIdRouteImport } from './routes/dashboard.workspace.$clientId'
import { Route as DashboardTrainingIdRouteImport } from './routes/dashboard.training.$id'
import { Route as DashboardTracksTrackSlugRouteImport } from './routes/dashboard.tracks.$trackSlug'
import { Route as DashboardSettingsTeamAccessRouteImport } from './routes/dashboard.settings.team-access'
import { Route as DashboardSettingsBankMappingRouteImport } from './routes/dashboard.settings.bank-mapping'
import { Route as DashboardProgramsProgramIdRouteImport } from './routes/dashboard.programs.$programId'
import { Route as DashboardHiveExecTicketsRouteImport } from './routes/dashboard.hive-exec.tickets'
import { Route as DashboardHiveExecPlansRouteImport } from './routes/dashboard.hive-exec.plans'
import { Route as DashboardHiveExecHealthRouteImport } from './routes/dashboard.hive-exec.health'
import { Route as DashboardHiveExecOrgIdRouteImport } from './routes/dashboard.hive-exec.$orgId'
import { Route as DashboardHhsHubClientIdRouteImport } from './routes/dashboard.hhs-hub.$clientId'
import { Route as DashboardCoursesMindsmithRouteImport } from './routes/dashboard.courses.mindsmith'
import { Route as DashboardCoursesCourseIdRouteImport } from './routes/dashboard.courses.$courseId'
import { Route as DashboardBillingNectarRouteImport } from './routes/dashboard.billing.nectar'
import { Route as DashboardBillingImportsRouteImport } from './routes/dashboard.billing.imports'
import { Route as DashboardBillingForm520RouteImport } from './routes/dashboard.billing.form520'
import { Route as DashboardBillingClientIdRouteImport } from './routes/dashboard.billing.$clientId'
import { Route as DashboardAdminEmarAuditRouteImport } from './routes/dashboard.admin.emar-audit'
import { Route as ApiPublicSeedStaffRouteImport } from './routes/api/public/seed-staff'
import { Route as DashboardCoursesCourseIdEditRouteImport } from './routes/dashboard.courses.$courseId.edit'
import { Route as ApiPublicHooksNectarSchedulesRouteImport } from './routes/api/public/hooks/nectar-schedules'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FixAdminRoute = FixAdminRouteImport.update({
  id: '/fix-admin',
  path: '/fix-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTracksRoute = DashboardTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimeclockRoute = DashboardTimeclockRouteImport.update({
  id: '/timeclock',
  path: '/timeclock',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperAdminRoute = DashboardSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulingRoute = DashboardSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReimbursementsRoute = DashboardReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsDeskRoute = DashboardRecordsDeskRouteImport.update({
  id: '/records-desk',
  path: '/records-desk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsAdminRoute = DashboardProgramsAdminRouteImport.update({
  id: '/programs-admin',
  path: '/programs-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPermissionsRoute = DashboardPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPbaLedgerRoute = DashboardPbaLedgerRouteImport.update({
  id: '/pba-ledger',
  path: '/pba-ledger',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNectarDocsRoute = DashboardNectarDocsRouteImport.update({
  id: '/nectar-docs',
  path: '/nectar-docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostHomeControlRoute =
  DashboardHostHomeControlRouteImport.update({
    id: '/host-home-control',
    path: '/host-home-control',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardHiveExecRoute = DashboardHiveExecRouteImport.update({
  id: '/hive-exec',
  path: '/hive-exec',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExternalCertificationsRoute =
  DashboardExternalCertificationsRouteImport.update({
    id: '/external-certifications',
    path: '/external-certifications',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmarRoute = DashboardEmarRouteImport.update({
  id: '/emar',
  path: '/emar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDailyLogsRoute = DashboardDailyLogsRouteImport.update({
  id: '/daily-logs',
  path: '/daily-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceDeskRoute = DashboardComplianceDeskRouteImport.update({
  id: '/compliance-desk',
  path: '/compliance-desk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommandCenterRoute = DashboardCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientBillingCodesRoute =
  DashboardClientBillingCodesRouteImport.update({
    id: '/client-billing-codes',
    path: '/client-billing-codes',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCertificationsRoute = DashboardCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBilling520Route = DashboardBilling520RouteImport.update({
  id: '/billing-520',
  path: '/billing-520',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrainingIndexRoute = DashboardTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHiveExecIndexRoute = DashboardHiveExecIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardHiveExecRoute,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBillingRoute,
} as any)
const DashboardWorkspaceClientIdRoute =
  DashboardWorkspaceClientIdRouteImport.update({
    id: '/workspace/$clientId',
    path: '/workspace/$clientId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTrainingIdRoute = DashboardTrainingIdRouteImport.update({
  id: '/training/$id',
  path: '/training/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracksTrackSlugRoute =
  DashboardTracksTrackSlugRouteImport.update({
    id: '/$trackSlug',
    path: '/$trackSlug',
    getParentRoute: () => DashboardTracksRoute,
  } as any)
const DashboardSettingsTeamAccessRoute =
  DashboardSettingsTeamAccessRouteImport.update({
    id: '/team-access',
    path: '/team-access',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsBankMappingRoute =
  DashboardSettingsBankMappingRouteImport.update({
    id: '/bank-mapping',
    path: '/bank-mapping',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardProgramsProgramIdRoute =
  DashboardProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => DashboardProgramsRoute,
  } as any)
const DashboardHiveExecTicketsRoute =
  DashboardHiveExecTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => DashboardHiveExecRoute,
  } as any)
const DashboardHiveExecPlansRoute = DashboardHiveExecPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardHiveExecRoute,
} as any)
const DashboardHiveExecHealthRoute = DashboardHiveExecHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => DashboardHiveExecRoute,
} as any)
const DashboardHiveExecOrgIdRoute = DashboardHiveExecOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => DashboardHiveExecRoute,
} as any)
const DashboardHhsHubClientIdRoute = DashboardHhsHubClientIdRouteImport.update({
  id: '/hhs-hub/$clientId',
  path: '/hhs-hub/$clientId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesMindsmithRoute =
  DashboardCoursesMindsmithRouteImport.update({
    id: '/courses/mindsmith',
    path: '/courses/mindsmith',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesCourseIdRoute =
  DashboardCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBillingNectarRoute = DashboardBillingNectarRouteImport.update({
  id: '/nectar',
  path: '/nectar',
  getParentRoute: () => DashboardBillingRoute,
} as any)
const DashboardBillingImportsRoute = DashboardBillingImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => DashboardBillingRoute,
} as any)
const DashboardBillingForm520Route = DashboardBillingForm520RouteImport.update({
  id: '/form520',
  path: '/form520',
  getParentRoute: () => DashboardBillingRoute,
} as any)
const DashboardBillingClientIdRoute =
  DashboardBillingClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => DashboardBillingRoute,
  } as any)
const DashboardAdminEmarAuditRoute = DashboardAdminEmarAuditRouteImport.update({
  id: '/admin/emar-audit',
  path: '/admin/emar-audit',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicSeedStaffRoute = ApiPublicSeedStaffRouteImport.update({
  id: '/api/public/seed-staff',
  path: '/api/public/seed-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoursesCourseIdEditRoute =
  DashboardCoursesCourseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardCoursesCourseIdRoute,
  } as any)
const ApiPublicHooksNectarSchedulesRoute =
  ApiPublicHooksNectarSchedulesRouteImport.update({
    id: '/api/public/hooks/nectar-schedules',
    path: '/api/public/hooks/nectar-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRoute
  '/fix-admin': typeof FixAdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/billing-520': typeof DashboardBilling520Route
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/client-billing-codes': typeof DashboardClientBillingCodesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/command-center': typeof DashboardCommandCenterRoute
  '/dashboard/compliance-desk': typeof DashboardComplianceDeskRoute
  '/dashboard/daily-logs': typeof DashboardDailyLogsRoute
  '/dashboard/emar': typeof DashboardEmarRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/external-certifications': typeof DashboardExternalCertificationsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/hive-exec': typeof DashboardHiveExecRouteWithChildren
  '/dashboard/host-home-control': typeof DashboardHostHomeControlRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/nectar-docs': typeof DashboardNectarDocsRoute
  '/dashboard/pba-ledger': typeof DashboardPbaLedgerRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/programs-admin': typeof DashboardProgramsAdminRoute
  '/dashboard/records-desk': typeof DashboardRecordsDeskRoute
  '/dashboard/reimbursements': typeof DashboardReimbursementsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/scheduling': typeof DashboardSchedulingRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/timeclock': typeof DashboardTimeclockRoute
  '/dashboard/tracks': typeof DashboardTracksRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/seed-staff': typeof ApiPublicSeedStaffRoute
  '/dashboard/admin/emar-audit': typeof DashboardAdminEmarAuditRoute
  '/dashboard/billing/$clientId': typeof DashboardBillingClientIdRoute
  '/dashboard/billing/form520': typeof DashboardBillingForm520Route
  '/dashboard/billing/imports': typeof DashboardBillingImportsRoute
  '/dashboard/billing/nectar': typeof DashboardBillingNectarRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRouteWithChildren
  '/dashboard/courses/mindsmith': typeof DashboardCoursesMindsmithRoute
  '/dashboard/hhs-hub/$clientId': typeof DashboardHhsHubClientIdRoute
  '/dashboard/hive-exec/$orgId': typeof DashboardHiveExecOrgIdRoute
  '/dashboard/hive-exec/health': typeof DashboardHiveExecHealthRoute
  '/dashboard/hive-exec/plans': typeof DashboardHiveExecPlansRoute
  '/dashboard/hive-exec/tickets': typeof DashboardHiveExecTicketsRoute
  '/dashboard/programs/$programId': typeof DashboardProgramsProgramIdRoute
  '/dashboard/settings/bank-mapping': typeof DashboardSettingsBankMappingRoute
  '/dashboard/settings/team-access': typeof DashboardSettingsTeamAccessRoute
  '/dashboard/tracks/$trackSlug': typeof DashboardTracksTrackSlugRoute
  '/dashboard/training/$id': typeof DashboardTrainingIdRoute
  '/dashboard/workspace/$clientId': typeof DashboardWorkspaceClientIdRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/hive-exec/': typeof DashboardHiveExecIndexRoute
  '/dashboard/training/': typeof DashboardTrainingIndexRoute
  '/api/public/hooks/nectar-schedules': typeof ApiPublicHooksNectarSchedulesRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRoute
  '/fix-admin': typeof FixAdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/billing-520': typeof DashboardBilling520Route
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/client-billing-codes': typeof DashboardClientBillingCodesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/command-center': typeof DashboardCommandCenterRoute
  '/dashboard/compliance-desk': typeof DashboardComplianceDeskRoute
  '/dashboard/daily-logs': typeof DashboardDailyLogsRoute
  '/dashboard/emar': typeof DashboardEmarRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/external-certifications': typeof DashboardExternalCertificationsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/host-home-control': typeof DashboardHostHomeControlRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/nectar-docs': typeof DashboardNectarDocsRoute
  '/dashboard/pba-ledger': typeof DashboardPbaLedgerRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/programs-admin': typeof DashboardProgramsAdminRoute
  '/dashboard/records-desk': typeof DashboardRecordsDeskRoute
  '/dashboard/reimbursements': typeof DashboardReimbursementsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/scheduling': typeof DashboardSchedulingRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/timeclock': typeof DashboardTimeclockRoute
  '/dashboard/tracks': typeof DashboardTracksRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/seed-staff': typeof ApiPublicSeedStaffRoute
  '/dashboard/admin/emar-audit': typeof DashboardAdminEmarAuditRoute
  '/dashboard/billing/$clientId': typeof DashboardBillingClientIdRoute
  '/dashboard/billing/form520': typeof DashboardBillingForm520Route
  '/dashboard/billing/imports': typeof DashboardBillingImportsRoute
  '/dashboard/billing/nectar': typeof DashboardBillingNectarRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRouteWithChildren
  '/dashboard/courses/mindsmith': typeof DashboardCoursesMindsmithRoute
  '/dashboard/hhs-hub/$clientId': typeof DashboardHhsHubClientIdRoute
  '/dashboard/hive-exec/$orgId': typeof DashboardHiveExecOrgIdRoute
  '/dashboard/hive-exec/health': typeof DashboardHiveExecHealthRoute
  '/dashboard/hive-exec/plans': typeof DashboardHiveExecPlansRoute
  '/dashboard/hive-exec/tickets': typeof DashboardHiveExecTicketsRoute
  '/dashboard/programs/$programId': typeof DashboardProgramsProgramIdRoute
  '/dashboard/settings/bank-mapping': typeof DashboardSettingsBankMappingRoute
  '/dashboard/settings/team-access': typeof DashboardSettingsTeamAccessRoute
  '/dashboard/tracks/$trackSlug': typeof DashboardTracksTrackSlugRoute
  '/dashboard/training/$id': typeof DashboardTrainingIdRoute
  '/dashboard/workspace/$clientId': typeof DashboardWorkspaceClientIdRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/dashboard/hive-exec': typeof DashboardHiveExecIndexRoute
  '/dashboard/training': typeof DashboardTrainingIndexRoute
  '/api/public/hooks/nectar-schedules': typeof ApiPublicHooksNectarSchedulesRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRoute
  '/fix-admin': typeof FixAdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/billing-520': typeof DashboardBilling520Route
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/client-billing-codes': typeof DashboardClientBillingCodesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/command-center': typeof DashboardCommandCenterRoute
  '/dashboard/compliance-desk': typeof DashboardComplianceDeskRoute
  '/dashboard/daily-logs': typeof DashboardDailyLogsRoute
  '/dashboard/emar': typeof DashboardEmarRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/external-certifications': typeof DashboardExternalCertificationsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/hive-exec': typeof DashboardHiveExecRouteWithChildren
  '/dashboard/host-home-control': typeof DashboardHostHomeControlRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/nectar-docs': typeof DashboardNectarDocsRoute
  '/dashboard/pba-ledger': typeof DashboardPbaLedgerRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/programs-admin': typeof DashboardProgramsAdminRoute
  '/dashboard/records-desk': typeof DashboardRecordsDeskRoute
  '/dashboard/reimbursements': typeof DashboardReimbursementsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/scheduling': typeof DashboardSchedulingRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/timeclock': typeof DashboardTimeclockRoute
  '/dashboard/tracks': typeof DashboardTracksRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/seed-staff': typeof ApiPublicSeedStaffRoute
  '/dashboard/admin/emar-audit': typeof DashboardAdminEmarAuditRoute
  '/dashboard/billing/$clientId': typeof DashboardBillingClientIdRoute
  '/dashboard/billing/form520': typeof DashboardBillingForm520Route
  '/dashboard/billing/imports': typeof DashboardBillingImportsRoute
  '/dashboard/billing/nectar': typeof DashboardBillingNectarRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRouteWithChildren
  '/dashboard/courses/mindsmith': typeof DashboardCoursesMindsmithRoute
  '/dashboard/hhs-hub/$clientId': typeof DashboardHhsHubClientIdRoute
  '/dashboard/hive-exec/$orgId': typeof DashboardHiveExecOrgIdRoute
  '/dashboard/hive-exec/health': typeof DashboardHiveExecHealthRoute
  '/dashboard/hive-exec/plans': typeof DashboardHiveExecPlansRoute
  '/dashboard/hive-exec/tickets': typeof DashboardHiveExecTicketsRoute
  '/dashboard/programs/$programId': typeof DashboardProgramsProgramIdRoute
  '/dashboard/settings/bank-mapping': typeof DashboardSettingsBankMappingRoute
  '/dashboard/settings/team-access': typeof DashboardSettingsTeamAccessRoute
  '/dashboard/tracks/$trackSlug': typeof DashboardTracksTrackSlugRoute
  '/dashboard/training/$id': typeof DashboardTrainingIdRoute
  '/dashboard/workspace/$clientId': typeof DashboardWorkspaceClientIdRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/hive-exec/': typeof DashboardHiveExecIndexRoute
  '/dashboard/training/': typeof DashboardTrainingIndexRoute
  '/api/public/hooks/nectar-schedules': typeof ApiPublicHooksNectarSchedulesRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/fix-admin'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/unauthorized'
    | '/certificate/$code'
    | '/dashboard/assignments'
    | '/dashboard/audit'
    | '/dashboard/billing'
    | '/dashboard/billing-520'
    | '/dashboard/certifications'
    | '/dashboard/client-billing-codes'
    | '/dashboard/clients'
    | '/dashboard/command-center'
    | '/dashboard/compliance-desk'
    | '/dashboard/daily-logs'
    | '/dashboard/emar'
    | '/dashboard/employees'
    | '/dashboard/external-certifications'
    | '/dashboard/help'
    | '/dashboard/hive-exec'
    | '/dashboard/host-home-control'
    | '/dashboard/invitations'
    | '/dashboard/nectar-docs'
    | '/dashboard/pba-ledger'
    | '/dashboard/permissions'
    | '/dashboard/programs'
    | '/dashboard/programs-admin'
    | '/dashboard/records-desk'
    | '/dashboard/reimbursements'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/scheduling'
    | '/dashboard/settings'
    | '/dashboard/super-admin'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/timeclock'
    | '/dashboard/tracks'
    | '/verify/$code'
    | '/dashboard/'
    | '/api/public/seed-staff'
    | '/dashboard/admin/emar-audit'
    | '/dashboard/billing/$clientId'
    | '/dashboard/billing/form520'
    | '/dashboard/billing/imports'
    | '/dashboard/billing/nectar'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/mindsmith'
    | '/dashboard/hhs-hub/$clientId'
    | '/dashboard/hive-exec/$orgId'
    | '/dashboard/hive-exec/health'
    | '/dashboard/hive-exec/plans'
    | '/dashboard/hive-exec/tickets'
    | '/dashboard/programs/$programId'
    | '/dashboard/settings/bank-mapping'
    | '/dashboard/settings/team-access'
    | '/dashboard/tracks/$trackSlug'
    | '/dashboard/training/$id'
    | '/dashboard/workspace/$clientId'
    | '/dashboard/billing/'
    | '/dashboard/courses/'
    | '/dashboard/hive-exec/'
    | '/dashboard/training/'
    | '/api/public/hooks/nectar-schedules'
    | '/dashboard/courses/$courseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/employee'
    | '/fix-admin'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/unauthorized'
    | '/certificate/$code'
    | '/dashboard/assignments'
    | '/dashboard/audit'
    | '/dashboard/billing-520'
    | '/dashboard/certifications'
    | '/dashboard/client-billing-codes'
    | '/dashboard/clients'
    | '/dashboard/command-center'
    | '/dashboard/compliance-desk'
    | '/dashboard/daily-logs'
    | '/dashboard/emar'
    | '/dashboard/employees'
    | '/dashboard/external-certifications'
    | '/dashboard/help'
    | '/dashboard/host-home-control'
    | '/dashboard/invitations'
    | '/dashboard/nectar-docs'
    | '/dashboard/pba-ledger'
    | '/dashboard/permissions'
    | '/dashboard/programs'
    | '/dashboard/programs-admin'
    | '/dashboard/records-desk'
    | '/dashboard/reimbursements'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/scheduling'
    | '/dashboard/settings'
    | '/dashboard/super-admin'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/timeclock'
    | '/dashboard/tracks'
    | '/verify/$code'
    | '/dashboard'
    | '/api/public/seed-staff'
    | '/dashboard/admin/emar-audit'
    | '/dashboard/billing/$clientId'
    | '/dashboard/billing/form520'
    | '/dashboard/billing/imports'
    | '/dashboard/billing/nectar'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/mindsmith'
    | '/dashboard/hhs-hub/$clientId'
    | '/dashboard/hive-exec/$orgId'
    | '/dashboard/hive-exec/health'
    | '/dashboard/hive-exec/plans'
    | '/dashboard/hive-exec/tickets'
    | '/dashboard/programs/$programId'
    | '/dashboard/settings/bank-mapping'
    | '/dashboard/settings/team-access'
    | '/dashboard/tracks/$trackSlug'
    | '/dashboard/training/$id'
    | '/dashboard/workspace/$clientId'
    | '/dashboard/billing'
    | '/dashboard/courses'
    | '/dashboard/hive-exec'
    | '/dashboard/training'
    | '/api/public/hooks/nectar-schedules'
    | '/dashboard/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/fix-admin'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/unauthorized'
    | '/certificate/$code'
    | '/dashboard/assignments'
    | '/dashboard/audit'
    | '/dashboard/billing'
    | '/dashboard/billing-520'
    | '/dashboard/certifications'
    | '/dashboard/client-billing-codes'
    | '/dashboard/clients'
    | '/dashboard/command-center'
    | '/dashboard/compliance-desk'
    | '/dashboard/daily-logs'
    | '/dashboard/emar'
    | '/dashboard/employees'
    | '/dashboard/external-certifications'
    | '/dashboard/help'
    | '/dashboard/hive-exec'
    | '/dashboard/host-home-control'
    | '/dashboard/invitations'
    | '/dashboard/nectar-docs'
    | '/dashboard/pba-ledger'
    | '/dashboard/permissions'
    | '/dashboard/programs'
    | '/dashboard/programs-admin'
    | '/dashboard/records-desk'
    | '/dashboard/reimbursements'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/scheduling'
    | '/dashboard/settings'
    | '/dashboard/super-admin'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/timeclock'
    | '/dashboard/tracks'
    | '/verify/$code'
    | '/dashboard/'
    | '/api/public/seed-staff'
    | '/dashboard/admin/emar-audit'
    | '/dashboard/billing/$clientId'
    | '/dashboard/billing/form520'
    | '/dashboard/billing/imports'
    | '/dashboard/billing/nectar'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/mindsmith'
    | '/dashboard/hhs-hub/$clientId'
    | '/dashboard/hive-exec/$orgId'
    | '/dashboard/hive-exec/health'
    | '/dashboard/hive-exec/plans'
    | '/dashboard/hive-exec/tickets'
    | '/dashboard/programs/$programId'
    | '/dashboard/settings/bank-mapping'
    | '/dashboard/settings/team-access'
    | '/dashboard/tracks/$trackSlug'
    | '/dashboard/training/$id'
    | '/dashboard/workspace/$clientId'
    | '/dashboard/billing/'
    | '/dashboard/courses/'
    | '/dashboard/hive-exec/'
    | '/dashboard/training/'
    | '/api/public/hooks/nectar-schedules'
    | '/dashboard/courses/$courseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeeRoute: typeof EmployeeRoute
  FixAdminRoute: typeof FixAdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiPublicSeedStaffRoute: typeof ApiPublicSeedStaffRoute
  ApiPublicHooksNectarSchedulesRoute: typeof ApiPublicHooksNectarSchedulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-admin': {
      id: '/fix-admin'
      path: '/fix-admin'
      fullPath: '/fix-admin'
      preLoaderRoute: typeof FixAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tracks': {
      id: '/dashboard/tracks'
      path: '/tracks'
      fullPath: '/dashboard/tracks'
      preLoaderRoute: typeof DashboardTracksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timeclock': {
      id: '/dashboard/timeclock'
      path: '/timeclock'
      fullPath: '/dashboard/timeclock'
      preLoaderRoute: typeof DashboardTimeclockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/super-admin': {
      id: '/dashboard/super-admin'
      path: '/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof DashboardSuperAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scheduling': {
      id: '/dashboard/scheduling'
      path: '/scheduling'
      fullPath: '/dashboard/scheduling'
      preLoaderRoute: typeof DashboardSchedulingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reimbursements': {
      id: '/dashboard/reimbursements'
      path: '/reimbursements'
      fullPath: '/dashboard/reimbursements'
      preLoaderRoute: typeof DashboardReimbursementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records-desk': {
      id: '/dashboard/records-desk'
      path: '/records-desk'
      fullPath: '/dashboard/records-desk'
      preLoaderRoute: typeof DashboardRecordsDeskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs-admin': {
      id: '/dashboard/programs-admin'
      path: '/programs-admin'
      fullPath: '/dashboard/programs-admin'
      preLoaderRoute: typeof DashboardProgramsAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs': {
      id: '/dashboard/programs'
      path: '/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/permissions': {
      id: '/dashboard/permissions'
      path: '/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof DashboardPermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pba-ledger': {
      id: '/dashboard/pba-ledger'
      path: '/pba-ledger'
      fullPath: '/dashboard/pba-ledger'
      preLoaderRoute: typeof DashboardPbaLedgerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nectar-docs': {
      id: '/dashboard/nectar-docs'
      path: '/nectar-docs'
      fullPath: '/dashboard/nectar-docs'
      preLoaderRoute: typeof DashboardNectarDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/host-home-control': {
      id: '/dashboard/host-home-control'
      path: '/host-home-control'
      fullPath: '/dashboard/host-home-control'
      preLoaderRoute: typeof DashboardHostHomeControlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hive-exec': {
      id: '/dashboard/hive-exec'
      path: '/hive-exec'
      fullPath: '/dashboard/hive-exec'
      preLoaderRoute: typeof DashboardHiveExecRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/external-certifications': {
      id: '/dashboard/external-certifications'
      path: '/external-certifications'
      fullPath: '/dashboard/external-certifications'
      preLoaderRoute: typeof DashboardExternalCertificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees': {
      id: '/dashboard/employees'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emar': {
      id: '/dashboard/emar'
      path: '/emar'
      fullPath: '/dashboard/emar'
      preLoaderRoute: typeof DashboardEmarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/daily-logs': {
      id: '/dashboard/daily-logs'
      path: '/daily-logs'
      fullPath: '/dashboard/daily-logs'
      preLoaderRoute: typeof DashboardDailyLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance-desk': {
      id: '/dashboard/compliance-desk'
      path: '/compliance-desk'
      fullPath: '/dashboard/compliance-desk'
      preLoaderRoute: typeof DashboardComplianceDeskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/command-center': {
      id: '/dashboard/command-center'
      path: '/command-center'
      fullPath: '/dashboard/command-center'
      preLoaderRoute: typeof DashboardCommandCenterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-billing-codes': {
      id: '/dashboard/client-billing-codes'
      path: '/client-billing-codes'
      fullPath: '/dashboard/client-billing-codes'
      preLoaderRoute: typeof DashboardClientBillingCodesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certifications': {
      id: '/dashboard/certifications'
      path: '/certifications'
      fullPath: '/dashboard/certifications'
      preLoaderRoute: typeof DashboardCertificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing-520': {
      id: '/dashboard/billing-520'
      path: '/billing-520'
      fullPath: '/dashboard/billing-520'
      preLoaderRoute: typeof DashboardBilling520RouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/training/': {
      id: '/dashboard/training/'
      path: '/training'
      fullPath: '/dashboard/training/'
      preLoaderRoute: typeof DashboardTrainingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hive-exec/': {
      id: '/dashboard/hive-exec/'
      path: '/'
      fullPath: '/dashboard/hive-exec/'
      preLoaderRoute: typeof DashboardHiveExecIndexRouteImport
      parentRoute: typeof DashboardHiveExecRoute
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/courses'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/workspace/$clientId': {
      id: '/dashboard/workspace/$clientId'
      path: '/workspace/$clientId'
      fullPath: '/dashboard/workspace/$clientId'
      preLoaderRoute: typeof DashboardWorkspaceClientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/training/$id': {
      id: '/dashboard/training/$id'
      path: '/training/$id'
      fullPath: '/dashboard/training/$id'
      preLoaderRoute: typeof DashboardTrainingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracks/$trackSlug': {
      id: '/dashboard/tracks/$trackSlug'
      path: '/$trackSlug'
      fullPath: '/dashboard/tracks/$trackSlug'
      preLoaderRoute: typeof DashboardTracksTrackSlugRouteImport
      parentRoute: typeof DashboardTracksRoute
    }
    '/dashboard/settings/team-access': {
      id: '/dashboard/settings/team-access'
      path: '/team-access'
      fullPath: '/dashboard/settings/team-access'
      preLoaderRoute: typeof DashboardSettingsTeamAccessRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/bank-mapping': {
      id: '/dashboard/settings/bank-mapping'
      path: '/bank-mapping'
      fullPath: '/dashboard/settings/bank-mapping'
      preLoaderRoute: typeof DashboardSettingsBankMappingRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/programs/$programId': {
      id: '/dashboard/programs/$programId'
      path: '/$programId'
      fullPath: '/dashboard/programs/$programId'
      preLoaderRoute: typeof DashboardProgramsProgramIdRouteImport
      parentRoute: typeof DashboardProgramsRoute
    }
    '/dashboard/hive-exec/tickets': {
      id: '/dashboard/hive-exec/tickets'
      path: '/tickets'
      fullPath: '/dashboard/hive-exec/tickets'
      preLoaderRoute: typeof DashboardHiveExecTicketsRouteImport
      parentRoute: typeof DashboardHiveExecRoute
    }
    '/dashboard/hive-exec/plans': {
      id: '/dashboard/hive-exec/plans'
      path: '/plans'
      fullPath: '/dashboard/hive-exec/plans'
      preLoaderRoute: typeof DashboardHiveExecPlansRouteImport
      parentRoute: typeof DashboardHiveExecRoute
    }
    '/dashboard/hive-exec/health': {
      id: '/dashboard/hive-exec/health'
      path: '/health'
      fullPath: '/dashboard/hive-exec/health'
      preLoaderRoute: typeof DashboardHiveExecHealthRouteImport
      parentRoute: typeof DashboardHiveExecRoute
    }
    '/dashboard/hive-exec/$orgId': {
      id: '/dashboard/hive-exec/$orgId'
      path: '/$orgId'
      fullPath: '/dashboard/hive-exec/$orgId'
      preLoaderRoute: typeof DashboardHiveExecOrgIdRouteImport
      parentRoute: typeof DashboardHiveExecRoute
    }
    '/dashboard/hhs-hub/$clientId': {
      id: '/dashboard/hhs-hub/$clientId'
      path: '/hhs-hub/$clientId'
      fullPath: '/dashboard/hhs-hub/$clientId'
      preLoaderRoute: typeof DashboardHhsHubClientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/mindsmith': {
      id: '/dashboard/courses/mindsmith'
      path: '/courses/mindsmith'
      fullPath: '/dashboard/courses/mindsmith'
      preLoaderRoute: typeof DashboardCoursesMindsmithRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$courseId': {
      id: '/dashboard/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/dashboard/courses/$courseId'
      preLoaderRoute: typeof DashboardCoursesCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing/nectar': {
      id: '/dashboard/billing/nectar'
      path: '/nectar'
      fullPath: '/dashboard/billing/nectar'
      preLoaderRoute: typeof DashboardBillingNectarRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/billing/imports': {
      id: '/dashboard/billing/imports'
      path: '/imports'
      fullPath: '/dashboard/billing/imports'
      preLoaderRoute: typeof DashboardBillingImportsRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/billing/form520': {
      id: '/dashboard/billing/form520'
      path: '/form520'
      fullPath: '/dashboard/billing/form520'
      preLoaderRoute: typeof DashboardBillingForm520RouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/billing/$clientId': {
      id: '/dashboard/billing/$clientId'
      path: '/$clientId'
      fullPath: '/dashboard/billing/$clientId'
      preLoaderRoute: typeof DashboardBillingClientIdRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/admin/emar-audit': {
      id: '/dashboard/admin/emar-audit'
      path: '/admin/emar-audit'
      fullPath: '/dashboard/admin/emar-audit'
      preLoaderRoute: typeof DashboardAdminEmarAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/seed-staff': {
      id: '/api/public/seed-staff'
      path: '/api/public/seed-staff'
      fullPath: '/api/public/seed-staff'
      preLoaderRoute: typeof ApiPublicSeedStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/courses/$courseId/edit': {
      id: '/dashboard/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/dashboard/courses/$courseId/edit'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditRouteImport
      parentRoute: typeof DashboardCoursesCourseIdRoute
    }
    '/api/public/hooks/nectar-schedules': {
      id: '/api/public/hooks/nectar-schedules'
      path: '/api/public/hooks/nectar-schedules'
      fullPath: '/api/public/hooks/nectar-schedules'
      preLoaderRoute: typeof ApiPublicHooksNectarSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardBillingRouteChildren {
  DashboardBillingClientIdRoute: typeof DashboardBillingClientIdRoute
  DashboardBillingForm520Route: typeof DashboardBillingForm520Route
  DashboardBillingImportsRoute: typeof DashboardBillingImportsRoute
  DashboardBillingNectarRoute: typeof DashboardBillingNectarRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
}

const DashboardBillingRouteChildren: DashboardBillingRouteChildren = {
  DashboardBillingClientIdRoute: DashboardBillingClientIdRoute,
  DashboardBillingForm520Route: DashboardBillingForm520Route,
  DashboardBillingImportsRoute: DashboardBillingImportsRoute,
  DashboardBillingNectarRoute: DashboardBillingNectarRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
}

const DashboardBillingRouteWithChildren =
  DashboardBillingRoute._addFileChildren(DashboardBillingRouteChildren)

interface DashboardHiveExecRouteChildren {
  DashboardHiveExecOrgIdRoute: typeof DashboardHiveExecOrgIdRoute
  DashboardHiveExecHealthRoute: typeof DashboardHiveExecHealthRoute
  DashboardHiveExecPlansRoute: typeof DashboardHiveExecPlansRoute
  DashboardHiveExecTicketsRoute: typeof DashboardHiveExecTicketsRoute
  DashboardHiveExecIndexRoute: typeof DashboardHiveExecIndexRoute
}

const DashboardHiveExecRouteChildren: DashboardHiveExecRouteChildren = {
  DashboardHiveExecOrgIdRoute: DashboardHiveExecOrgIdRoute,
  DashboardHiveExecHealthRoute: DashboardHiveExecHealthRoute,
  DashboardHiveExecPlansRoute: DashboardHiveExecPlansRoute,
  DashboardHiveExecTicketsRoute: DashboardHiveExecTicketsRoute,
  DashboardHiveExecIndexRoute: DashboardHiveExecIndexRoute,
}

const DashboardHiveExecRouteWithChildren =
  DashboardHiveExecRoute._addFileChildren(DashboardHiveExecRouteChildren)

interface DashboardProgramsRouteChildren {
  DashboardProgramsProgramIdRoute: typeof DashboardProgramsProgramIdRoute
}

const DashboardProgramsRouteChildren: DashboardProgramsRouteChildren = {
  DashboardProgramsProgramIdRoute: DashboardProgramsProgramIdRoute,
}

const DashboardProgramsRouteWithChildren =
  DashboardProgramsRoute._addFileChildren(DashboardProgramsRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsBankMappingRoute: typeof DashboardSettingsBankMappingRoute
  DashboardSettingsTeamAccessRoute: typeof DashboardSettingsTeamAccessRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsBankMappingRoute: DashboardSettingsBankMappingRoute,
  DashboardSettingsTeamAccessRoute: DashboardSettingsTeamAccessRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardTracksRouteChildren {
  DashboardTracksTrackSlugRoute: typeof DashboardTracksTrackSlugRoute
}

const DashboardTracksRouteChildren: DashboardTracksRouteChildren = {
  DashboardTracksTrackSlugRoute: DashboardTracksTrackSlugRoute,
}

const DashboardTracksRouteWithChildren = DashboardTracksRoute._addFileChildren(
  DashboardTracksRouteChildren,
)

interface DashboardCoursesCourseIdRouteChildren {
  DashboardCoursesCourseIdEditRoute: typeof DashboardCoursesCourseIdEditRoute
}

const DashboardCoursesCourseIdRouteChildren: DashboardCoursesCourseIdRouteChildren =
  {
    DashboardCoursesCourseIdEditRoute: DashboardCoursesCourseIdEditRoute,
  }

const DashboardCoursesCourseIdRouteWithChildren =
  DashboardCoursesCourseIdRoute._addFileChildren(
    DashboardCoursesCourseIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardBillingRoute: typeof DashboardBillingRouteWithChildren
  DashboardBilling520Route: typeof DashboardBilling520Route
  DashboardCertificationsRoute: typeof DashboardCertificationsRoute
  DashboardClientBillingCodesRoute: typeof DashboardClientBillingCodesRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardCommandCenterRoute: typeof DashboardCommandCenterRoute
  DashboardComplianceDeskRoute: typeof DashboardComplianceDeskRoute
  DashboardDailyLogsRoute: typeof DashboardDailyLogsRoute
  DashboardEmarRoute: typeof DashboardEmarRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardExternalCertificationsRoute: typeof DashboardExternalCertificationsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardHiveExecRoute: typeof DashboardHiveExecRouteWithChildren
  DashboardHostHomeControlRoute: typeof DashboardHostHomeControlRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardNectarDocsRoute: typeof DashboardNectarDocsRoute
  DashboardPbaLedgerRoute: typeof DashboardPbaLedgerRoute
  DashboardPermissionsRoute: typeof DashboardPermissionsRoute
  DashboardProgramsRoute: typeof DashboardProgramsRouteWithChildren
  DashboardProgramsAdminRoute: typeof DashboardProgramsAdminRoute
  DashboardRecordsDeskRoute: typeof DashboardRecordsDeskRoute
  DashboardReimbursementsRoute: typeof DashboardReimbursementsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardSchedulingRoute: typeof DashboardSchedulingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardSuperAdminRoute: typeof DashboardSuperAdminRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardTimeclockRoute: typeof DashboardTimeclockRoute
  DashboardTracksRoute: typeof DashboardTracksRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminEmarAuditRoute: typeof DashboardAdminEmarAuditRoute
  DashboardCoursesCourseIdRoute: typeof DashboardCoursesCourseIdRouteWithChildren
  DashboardCoursesMindsmithRoute: typeof DashboardCoursesMindsmithRoute
  DashboardHhsHubClientIdRoute: typeof DashboardHhsHubClientIdRoute
  DashboardTrainingIdRoute: typeof DashboardTrainingIdRoute
  DashboardWorkspaceClientIdRoute: typeof DashboardWorkspaceClientIdRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
  DashboardTrainingIndexRoute: typeof DashboardTrainingIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardBillingRoute: DashboardBillingRouteWithChildren,
  DashboardBilling520Route: DashboardBilling520Route,
  DashboardCertificationsRoute: DashboardCertificationsRoute,
  DashboardClientBillingCodesRoute: DashboardClientBillingCodesRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardCommandCenterRoute: DashboardCommandCenterRoute,
  DashboardComplianceDeskRoute: DashboardComplianceDeskRoute,
  DashboardDailyLogsRoute: DashboardDailyLogsRoute,
  DashboardEmarRoute: DashboardEmarRoute,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardExternalCertificationsRoute: DashboardExternalCertificationsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardHiveExecRoute: DashboardHiveExecRouteWithChildren,
  DashboardHostHomeControlRoute: DashboardHostHomeControlRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardNectarDocsRoute: DashboardNectarDocsRoute,
  DashboardPbaLedgerRoute: DashboardPbaLedgerRoute,
  DashboardPermissionsRoute: DashboardPermissionsRoute,
  DashboardProgramsRoute: DashboardProgramsRouteWithChildren,
  DashboardProgramsAdminRoute: DashboardProgramsAdminRoute,
  DashboardRecordsDeskRoute: DashboardRecordsDeskRoute,
  DashboardReimbursementsRoute: DashboardReimbursementsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardSchedulingRoute: DashboardSchedulingRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardSuperAdminRoute: DashboardSuperAdminRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardTimeclockRoute: DashboardTimeclockRoute,
  DashboardTracksRoute: DashboardTracksRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminEmarAuditRoute: DashboardAdminEmarAuditRoute,
  DashboardCoursesCourseIdRoute: DashboardCoursesCourseIdRouteWithChildren,
  DashboardCoursesMindsmithRoute: DashboardCoursesMindsmithRoute,
  DashboardHhsHubClientIdRoute: DashboardHhsHubClientIdRoute,
  DashboardTrainingIdRoute: DashboardTrainingIdRoute,
  DashboardWorkspaceClientIdRoute: DashboardWorkspaceClientIdRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
  DashboardTrainingIndexRoute: DashboardTrainingIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeeRoute: EmployeeRoute,
  FixAdminRoute: FixAdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiPublicSeedStaffRoute: ApiPublicSeedStaffRoute,
  ApiPublicHooksNectarSchedulesRoute: ApiPublicHooksNectarSchedulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
