// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// ws is required for Supabase realtime in Node.js < 22 (no native WebSocket)
import ws from 'ws';
import { supabase as e2eSupabase } from "../../../e2e/mocks/supabase-client";

function getEnv() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
}

function hasBrowserStorage(): boolean {
  try {
    return (
      typeof window !== 'undefined' &&
      typeof window.localStorage !== 'undefined' &&
      window.localStorage !== null
    );
  } catch {
    return false;
  }
}

// Persistent browser client — only instantiated when localStorage is confirmed available.
let _browserClient: ReturnType<typeof createClient<Database>> | null = null;
function getBrowserClient() {
  if (!_browserClient) {
    const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = getEnv();
    _browserClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: window.localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    });
  }
  return _browserClient;
}

// Stateless server client — used during SSR or when localStorage is unavailable.
let _serverClient: ReturnType<typeof createClient<Database>> | null = null;
function getServerClient() {
  if (!_serverClient) {
    const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = getEnv();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    _serverClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      realtime: { transport: ws as any },
    }) as unknown as NonNullable<typeof _serverClient>;
  }
  return _serverClient!;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as unknown as ReturnType<typeof createClient<Database>> & object, {
  get(_, prop, receiver) {
    if (import.meta.env.VITE_E2E_HARNESS === "1") {
      const value = (e2eSupabase as Record<string | symbol, unknown>)[prop];
      return typeof value === "function" ? (value as (...args: unknown[]) => unknown).bind(e2eSupabase) : value;
    }
    const client = hasBrowserStorage() ? getBrowserClient() : getServerClient();
    return Reflect.get(client, prop, receiver);
  },
});
