// Citation-by-citation coverage for the Utah DSPD DHHS91172 pack.
//
// Status meaning:
//   encoded          — locked catalog + seedable duty exists
//   live_artifact    — HIVE already produces the evidence; do not clone as a to-do
//   when_applicable  — encoded, but the SOW itself is conditional
//   intentional_omit — not a contractor calendar duty (definitions, operational
//                      constraint, or a service this pack lists but does not
//                      seed as a second register row)
//   gap              — a real duty HIVE has not encoded yet (must be empty
//                      for Article 1 contractor shalls)

export type PackCoverageStatus =
  | "encoded"
  | "live_artifact"
  | "when_applicable"
  | "intentional_omit"
  | "gap";

export type PackCoverageRow = {
  id: string;
  source: "sow" | "cst" | "review_tool";
  citation: string;
  title: string;
  status: PackCoverageStatus;
  note: string;
  catalog_titles?: string[];
  audit_item_ids?: string[];
  service_codes?: string[];
};

export const UTAH_DSPD_COVERAGE: PackCoverageRow[] = [
  // ── Article 1 ───────────────────────────────────────────────────────────
  {
    id: "sow-1.1",
    source: "sow",
    citation: "SOW §1.1",
    title: "Definitions",
    status: "intentional_omit",
    note: "Defined terms, not a contractor duty.",
  },
  {
    id: "sow-1.2",
    source: "sow",
    citation: "SOW §1.2",
    title: "Background / HCBS Settings Rule",
    status: "intentional_omit",
    note: "Purpose statement. HCBS compliance is encoded through HRC, the Human Rights Plan, and Person-record rows.",
  },
  {
    id: "sow-1.3",
    source: "sow",
    citation: "SOW §1.3",
    title: "Population — accept DHHS referrals",
    status: "intentional_omit",
    note: "Operational intake rule, not a calendar duty.",
  },
  {
    id: "sow-1.4-medicaid",
    source: "sow",
    citation: "SOW §1.4(1)",
    title: "Approved Medicaid provider (CSW / CTW / ABI)",
    status: "encoded",
    note: "Contractor enrollment. HIVE stores proof; DIH enrolls.",
    catalog_titles: ["Medicaid Provider Enrollment — Current"],
  },
  {
    id: "sow-1.4-upi",
    source: "sow",
    citation: "SOW §1.4(2)",
    title: "Current USTEPS and UPI accounts",
    status: "encoded",
    note: "Account + access forms. 1056 accept/reject is the live authorization workflow.",
    catalog_titles: ["USTEPS and UPI Contractor Accounts"],
  },
  {
    id: "sow-1.4-licenses",
    source: "sow",
    citation: "SOW §1.4(3)",
    title: "Licenses and certificates in each service article",
    status: "encoded",
    note: "Per-code OL / USOR / foster-care rows. §1.34 restates the same keep-current rule.",
    catalog_titles: [
      "OL Residential Support License — 4+ Persons per Site",
      "OL Residential Support Certification — 3 or Fewer Persons per Site",
      "OL Day Treatment License — 4+ Persons",
      "OL Day Support Certification — 3 or Fewer Persons",
      "Child Placing / Foster Care License (DHHS/OL) — PPS",
      "USOR Approved Vendor — Job Coaching (SEI)",
      "USOR Approved Vendor — Job Development (SJD)",
    ],
  },
  {
    id: "sow-1.5",
    source: "sow",
    citation: "SOW §1.5",
    title: "Staff minimum age",
    status: "intentional_omit",
    note: "HR eligibility rule (16 / 18 when driving or DCFS/DJJYS). Not a recurring register duty.",
  },
  {
    id: "sow-1.6",
    source: "sow",
    citation: "SOW §1.6",
    title: "Volunteer qualifications and training",
    status: "when_applicable",
    note: "Friends and chosen natural supports are not volunteers. Encoded as a standing file when volunteers are used.",
    catalog_titles: ["Volunteer Training File — When Volunteers Are Used"],
  },
  {
    id: "sow-1.7-medicaid-101",
    source: "sow",
    citation: "SOW §1.7(1)",
    title: "Contractor DHHS Medicaid 101 (30 days + annual)",
    status: "encoded",
    note: "Contractor-level. Staff still get the orientation topic under §1.8(4).",
    catalog_titles: ["DHHS Medicaid 101 Training — Contractor"],
  },
  {
    id: "sow-1.7-manuals",
    source: "sow",
    citation: "SOW §1.7(2)–(4)",
    title: "Medicaid manuals memo + R539 / DHHS rules",
    status: "encoded",
    note: "Annual contractor memo. Covers manuals, Medicaid rules, DSPD R539, and DHHS rules.",
    catalog_titles: ["Utah Medicaid Provider Manuals — Annual Memo"],
  },
  {
    id: "sow-1.8-file",
    source: "sow",
    citation: "SOW §1.8(3)",
    title: "Process to track and document staff training",
    status: "encoded",
    note: "HIVE is that file.",
    catalog_titles: ["Training Documentation File — Maintained"],
    audit_item_ids: ["IV-5"],
  },
  {
    id: "sow-1.8-orientation",
    source: "sow",
    citation: "SOW §1.8(4)",
    title: "30-day / before-alone orientation (A–W)",
    status: "encoded",
    note: "One hire-relative duty. Person-specific (O) is a separate staff+client instance.",
    catalog_titles: [
      "30-Day New Hire Orientation Training",
      "Client-Specific Training — [Client Name]",
    ],
    audit_item_ids: ["IV-6"],
  },
  {
    id: "sow-1.8-90day",
    source: "sow",
    citation: "SOW §1.8(5)",
    title: "CPR, First Aid, person-centered thinking (90 days)",
    status: "encoded",
    catalog_titles: [
      "CPR/First Aid Certification — Initial",
      "CPR/First Aid Certification — Renewal",
      "Person-Centered Thinking and Practices Training",
    ],
    audit_item_ids: ["IV-7"],
    note: "Initial 90 days; renewal follows the printed card.",
  },
  {
    id: "sow-1.8-behavior",
    source: "sow",
    citation: "SOW §1.8(6)",
    title: "Behavior-intervention certification (180 days / keep current)",
    status: "encoded",
    catalog_titles: ["Behavior Intervention Certification (SOAR/MANDT/PART/CPI/Safety Care)"],
    audit_item_ids: ["IV-8"],
    note: "N/A for staff who do not serve a Person with that risk profile.",
  },
  {
    id: "sow-1.8-ce",
    source: "sow",
    citation: "SOW §1.8(7)",
    title: "12-hour continuing education from year two",
    status: "encoded",
    catalog_titles: ["Annual 12-Hour Continuing Education"],
    audit_item_ids: ["IV-9"],
    note: "Hire-anniversary year, not a calendar year.",
  },
  {
    id: "sow-1.8-abi",
    source: "sow",
    citation: "SOW §1.8 ABI",
    title: "ABI training before working alone",
    status: "encoded",
    catalog_titles: ["ABI Training — Before Working Alone"],
    audit_item_ids: ["IV-10"],
    note: "Assigned only when the org serves ABI or a staff member is flagged requires_abi.",
  },
  {
    id: "sow-1.9-bg",
    source: "sow",
    citation: "SOW §1.9(2)",
    title: "Background screening in each staff file",
    status: "encoded",
    catalog_titles: ["Background Screening — Annual"],
    audit_item_ids: ["IV-BG"],
    note: "Staff-record element. Screening is done through OBP; HIVE stores the clearance.",
  },
  {
    id: "sow-1.9-training",
    source: "sow",
    citation: "SOW §1.9(3)",
    title: "Training documentation in each staff file",
    status: "encoded",
    catalog_titles: ["Training Documentation File — Maintained"],
    note: "Same standing file as §1.8(3).",
  },
  {
    id: "sow-1.9-creds",
    source: "sow",
    citation: "SOW §1.9(4)",
    title: "Educational credentials and licenses on file",
    status: "encoded",
    catalog_titles: ["Educational Credentials and Licenses — On File"],
    audit_item_ids: ["IV-1"],
    note: "Onboarding window is 30 days. Review tool highlights BCBA / RN / LPN when those codes are awarded.",
  },
  {
    id: "sow-1.9-disclosure",
    source: "sow",
    citation: "SOW §1.9(6) / §1.13(5)",
    title: "Medicaid Disclosure Form at hire and annually",
    status: "encoded",
    catalog_titles: ["Medicaid Disclosure Form — Annual"],
    note: "Form lives on the DSPD webpage. Upload the signed copy.",
  },
  {
    id: "sow-1.9-oig",
    source: "sow",
    citation: "SOW §1.9(7)",
    title: "Medicaid fraud / OIG exclusion check",
    status: "encoded",
    catalog_titles: ["Medicaid Fraud & Abuse Exclusion Screening — Annual"],
    audit_item_ids: ["IV-3"],
    note: "Run at exclusions.oig.hhs.gov, then upload confirmation.",
  },
  {
    id: "sow-1.9-other",
    source: "sow",
    citation: "SOW §1.9(1)(5)",
    title: "Staff contact info and performance evaluations",
    status: "live_artifact",
    note: "Personnel-file fields on the staff record. Not a second SOW to-do.",
  },
  {
    id: "sow-1.10-records",
    source: "sow",
    citation: "SOW §1.10",
    title: "Person records (identity, photo, contacts, plans, DNR)",
    status: "live_artifact",
    note: "The Person file in HIVE. Grievance acknowledgment is review-tool II-7.",
    audit_item_ids: ["II-7"],
  },
  {
    id: "sow-1.10-timesheet",
    source: "sow",
    citation: "SOW §1.10(7)",
    title: "Service-delivery documentation / timesheets",
    status: "live_artifact",
    note: "Time entries are the attendance record. HHS daily notes are the host-home summary.",
    audit_item_ids: ["III-1"],
  },
  {
    id: "sow-1.11",
    source: "sow",
    citation: "SOW §1.11",
    title: "Zoning / Life Safety / fire-health (when applicable)",
    status: "when_applicable",
    note: "SOW says when applicable for licensure. This is an OL-site operational fact, not a service-code hide.",
    catalog_titles: ["Zoning / Life Safety Code Compliance Documentation"],
  },
  {
    id: "sow-1.12",
    source: "sow",
    citation: "SOW §1.12",
    title: "Electronic Visit Verification",
    status: "live_artifact",
    note: "Authoritative list is src/lib/evv-codes.ts (COM, HSQ, PAC, ACA, CHA, RP2, RP3, SLH, SLN, CMP, CMS). HHS/DSI/SEI are payroll/evidence only.",
    audit_item_ids: ["III-2"],
  },
  {
    id: "sow-1.13-enroll",
    source: "sow",
    citation: "SOW §1.13",
    title: "Medicaid provider enrollment and manuals",
    status: "encoded",
    catalog_titles: [
      "Medicaid Provider Enrollment — Current",
      "Utah Medicaid Provider Manuals — Annual Memo",
    ],
    note: "Enrollment + annual familiarity. Staff disclosure is the separate §1.9(6) row.",
  },
  {
    id: "sow-1.13-notice",
    source: "sow",
    citation: "SOW §1.13(2)–(3)",
    title: "Medicaid provider change notifications",
    status: "encoded",
    catalog_titles: ["Medicaid Provider Change Notifications"],
    note: "7-day contact changes; 30-day ownership / name / EIN. Per-event standing file.",
  },
  {
    id: "sow-1.14",
    source: "sow",
    citation: "SOW §1.14",
    title: "Governing or policy-making board",
    status: "when_applicable",
    catalog_titles: ["Governing or Policy-Making Board Records"],
    note: "Only if the contractor has such a board. By-laws + quarterly minutes.",
  },
  {
    id: "sow-1.15",
    source: "sow",
    citation: "SOW §1.15",
    title: "UPI access forms, 1056, billing in UPI",
    status: "encoded",
    catalog_titles: ["USTEPS and UPI Contractor Accounts"],
    note: "0-9 / 0-8 forms are this duty. 1056 accept/reject within 15 days and UPI billing are live authorization / billing artifacts.",
  },
  {
    id: "sow-1.15-1056",
    source: "sow",
    citation: "SOW §1.15(4)",
    title: "Approve or reject 1056 within 15 calendar days",
    status: "live_artifact",
    note: "client_billing_codes / authorization workflow. No authorization → no shift, no billing.",
  },
  {
    id: "sow-1.16",
    source: "sow",
    citation: "SOW §1.16",
    title: "Marketing limitations",
    status: "intentional_omit",
    note: "Prohibited conduct, not a calendar file. Operating policies can restate it.",
  },
  {
    id: "sow-1.17",
    source: "sow",
    citation: "SOW §1.17",
    title: "Personnel policies and job descriptions",
    status: "encoded",
    catalog_titles: ["Personnel Policies and Job Descriptions"],
    note: "Standing policy file.",
  },
  {
    id: "sow-1.18",
    source: "sow",
    citation: "SOW §1.18",
    title: "Operating policies and procedures",
    status: "encoded",
    catalog_titles: ["Operating Policies and Procedures"],
    note: "Standing policy file (roles, transportation, grievances, emergencies).",
  },
  {
    id: "sow-1.19",
    source: "sow",
    citation: "SOW §1.19",
    title: "Cooperate with DHHS quality monitoring / remediation",
    status: "intentional_omit",
    note: "Triggered when DHHS issues a deficiency. Not a standing annual class. IQMP (CST 50) is the related standing file.",
    catalog_titles: ["Internal Quality Management Plan"],
  },
  {
    id: "sow-1.20",
    source: "sow",
    citation: "SOW §1.20",
    title: "Human Rights Committee + restriction documentation",
    status: "live_artifact",
    note: "HRC roster, meetings, and eight-element restriction records live in HIVE.",
    audit_item_ids: ["I-3", "II-8"],
  },
  {
    id: "sow-1.21",
    source: "sow",
    citation: "SOW §1.21",
    title: "Human Rights Plan",
    status: "when_applicable",
    catalog_titles: ["Human Rights Plan"],
    note: "Written plan, separate from the live HRC. N/A only if the contractor provides solely CHA, HSQ, or PBA.",
  },
  {
    id: "sow-1.22",
    source: "sow",
    citation: "SOW §1.22",
    title: "Person discharge procedure and summary",
    status: "encoded",
    catalog_titles: ["Person Discharge Process"],
    audit_item_ids: ["I-9"],
    note: "Written procedure on file. The discharge summary itself is produced when a Person leaves.",
  },
  {
    id: "sow-1.23-policy",
    source: "sow",
    citation: "SOW §1.23",
    title: "Health support policies",
    status: "encoded",
    catalog_titles: ["Health Support Policies and Procedures"],
    note: "Contractor policy file. Medical/dental/meds in the Person record are live artifacts.",
  },
  {
    id: "sow-1.23-records",
    source: "sow",
    citation: "SOW §1.23(h) / (b–c)",
    title: "Medical, dental, and medication records",
    status: "live_artifact",
    audit_item_ids: ["II-1", "II-2"],
    note: "Person file + eMAR. II-1 applies to RHS/PPS/HHS/SLH/overnight respite.",
  },
  {
    id: "sow-1.24",
    source: "sow",
    citation: "SOW §1.24",
    title: "Person-centered planning and Support Strategies",
    status: "encoded",
    catalog_titles: ["Support Strategies — [Client Name]"],
    audit_item_ids: ["II-3"],
    note: "Due 30 days after PCSP activation. BSP / Medical Care Plan substitute for BC and nursing.",
  },
  {
    id: "sow-1.25",
    source: "sow",
    citation: "SOW §1.25",
    title: "Quarterly / monthly progress summaries",
    status: "live_artifact",
    catalog_titles: [
      "SEI Monthly Summary — UPI Entry Attestation",
      "CMP/CMS Monthly Summaries — Submitted to SC",
      "SJD Monthly Summary — UPI Entry Attestation",
    ],
    audit_item_ids: ["II-6"],
    note: "Write in HIVE. Quarterly (due 15 days after quarter end) for HHS/RHS/DSI/SLH/SLN; monthly for SEI, SJD, CMP/CMS, PN1/PN2.",
  },
  {
    id: "sow-1.26",
    source: "sow",
    citation: "SOW §1.26",
    title: "Fatality notifications",
    status: "live_artifact",
    note: "Event-driven through the incident path. Family within 24 hours; SC and waivermanager@utah.gov by the next calendar day.",
  },
  {
    id: "sow-1.27",
    source: "sow",
    citation: "SOW §1.27",
    title: "Critical incident reports",
    status: "live_artifact",
    audit_item_ids: ["I-5"],
    note: "Write in HIVE. UPI entry within 24 hours is still outside HIVE.",
  },
  {
    id: "sow-1.28-funds",
    source: "sow",
    citation: "SOW §1.28",
    title: "Person funds, PBA, and emergency loans",
    status: "live_artifact",
    audit_item_ids: ["I-11", "II-PBA", "II-LOAN"],
    note: "Client-loans register + PBA review when awarded. Disclosure to DHHS QA is outside HIVE.",
  },
  {
    id: "sow-1.28-gifts",
    source: "sow",
    citation: "SOW §1.28(9)–(10)",
    title: "No money / purchases from contractor or staff",
    status: "encoded",
    catalog_titles: ["No Gifts or Purchases-from-Staff Process"],
    audit_item_ids: ["I-7"],
    note: "Written process the auditor can read.",
  },
  {
    id: "sow-1.29",
    source: "sow",
    citation: "SOW §1.29",
    title: "Kitchen privileges and nutrition (residential / overnight)",
    status: "live_artifact",
    note: "Operational + HRC if kitchen access is limited. Not a second calendar duty.",
    service_codes: ["SLH", "RHS", "PPS", "HHS"],
  },
  {
    id: "sow-1.30",
    source: "sow",
    citation: "SOW §1.30",
    title: "Transportation file (license, record, insurance)",
    status: "encoded",
    catalog_titles: ["Driving Record — On File (Transporting Staff)"],
    note: "Assigned to staff who transport. Annual from hire.",
  },
  {
    id: "sow-1.31",
    source: "sow",
    citation: "SOW §1.31",
    title: "Allow SC monitoring; furnish records on request",
    status: "intentional_omit",
    note: "Cooperation rule. Timesheets within 3 days of SC request is operational, not a standing class.",
  },
  {
    id: "sow-1.32",
    source: "sow",
    citation: "SOW §1.32",
    title: "Group services / mixed residential approvals",
    status: "intentional_omit",
    note: "When-applicable placement approval. Document in the Person file when it occurs; not a universal annual duty.",
  },
  {
    id: "sow-1.33",
    source: "sow",
    citation: "SOW §1.33",
    title: "DSPD Worksheet hours and 2:1 rights modification",
    status: "live_artifact",
    note: "Scheduling / billing vs worksheet. 2:1 needs an HRC rights-modification warning — not a second to-do.",
  },
  {
    id: "sow-1.34",
    source: "sow",
    citation: "SOW §1.34",
    title: "Maintain all required licenses and certifications",
    status: "encoded",
    note: "Covered by the per-code OL / USOR / foster-care rows under §1.4(3).",
    catalog_titles: [
      "OL Residential Support License — 4+ Persons per Site",
      "OL Day Treatment License — 4+ Persons",
    ],
  },
  {
    id: "sow-1.35",
    source: "sow",
    citation: "SOW §1.35",
    title: "Housemate informed-choice discussion",
    status: "when_applicable",
    catalog_titles: ["Housemate Informed-Choice Discussion"],
    service_codes: ["HHS", "PPS", "RHS"],
    note: "At placement and any housemate change on or after July 1, 2026.",
  },
  {
    id: "sow-1.36",
    source: "sow",
    citation: "SOW §1.36",
    title: "USDC transitions",
    status: "intentional_omit",
    note: "Rare event coordinated with the DHHS/DSPD Transition team. Not a standing annual class.",
  },

  // ── TNS-awarded code articles ───────────────────────────────────────────
  {
    id: "sow-8-dsi-delivery",
    source: "sow",
    citation: "SOW Article 8.1–8.4",
    title: "DSI direct-service and limitation rules",
    status: "live_artifact",
    service_codes: ["DSI"],
    note: "Service description, site vs community mix, and billing limits are enforced in scheduling / billing — not cloned as calendar to-dos.",
    audit_item_ids: ["III-3"],
  },
  {
    id: "sow-8.5",
    source: "sow",
    citation: "SOW §8.5",
    title: "DSI OL Day Treatment / Day Support / Community Based cert",
    status: "encoded",
    service_codes: ["DSI"],
    catalog_titles: [
      "OL Day Treatment License — 4+ Persons",
      "OL Day Support Certification — 3 or Fewer Persons",
    ],
    audit_item_ids: ["I-1-DSI"],
    note: "Community-only DSI uses Community Based Day Support certification when serving 3 or fewer.",
  },
  {
    id: "sow-8.6",
    source: "sow",
    citation: "SOW §8.6",
    title: "DSI fiscal-year outcome report (Google Form, Aug 30)",
    status: "encoded",
    service_codes: ["DSI"],
    catalog_titles: ["DSI Annual Outcome Report — Google Form Submission"],
    note: "Same Aug 30 Google Form pattern as HHS / SEI / Supported Living.",
  },
  {
    id: "sow-11-hhs-delivery",
    source: "sow",
    citation: "SOW Article 11.1–11.4",
    title: "HHS direct-service, inventory, room-and-board, daily note",
    status: "live_artifact",
    service_codes: ["HHS"],
    audit_item_ids: ["II-9", "II-10-HHS", "III-1", "III-HHS"],
    note: "Belongings, room-and-board, and Present + daily note are live artifacts. Hosts never clock.",
  },
  {
    id: "sow-11.3-drills",
    source: "sow",
    citation: "SOW §11.3(6)",
    title: "HHS quarterly evacuation drills",
    status: "encoded",
    service_codes: ["HHS"],
    catalog_titles: ["HHS Quarterly Evacuation Drills — All Sites"],
    note: "One instance per active HHS home. Due by quarter end.",
  },
  {
    id: "sow-11.5",
    source: "sow",
    citation: "SOW §11.5",
    title: "HHS Host Home Certification (initial + annual)",
    status: "encoded",
    service_codes: ["HHS"],
    catalog_titles: ["HHS Home Certification — Annual (DSPD Form)"],
    audit_item_ids: ["I-2-HHS"],
    note: "One instance per active HHS home.",
  },
  {
    id: "sow-11.6",
    source: "sow",
    citation: "SOW §11.6",
    title: "HHS hosts at least 21 years of age",
    status: "intentional_omit",
    service_codes: ["HHS"],
    note: "Host eligibility rule on the host record. Not a recurring register duty.",
  },
  {
    id: "sow-11.7",
    source: "sow",
    citation: "SOW §11.7",
    title: "HHS fiscal-year outcome report (Google Form, Aug 30)",
    status: "encoded",
    service_codes: ["HHS"],
    catalog_titles: ["HHS Annual Outcome Report — Google Form Submission"],
  },
  {
    id: "sow-30-sei-delivery",
    source: "sow",
    citation: "SOW Article 30.1–30.4 / 30.8",
    title: "SEI job-coaching delivery, CIE rules, UPI timesheets",
    status: "live_artifact",
    service_codes: ["SEI"],
    audit_item_ids: ["II-5", "III-3"],
    note: "Employment plan / CIE constraints and UPI timesheet fields are live delivery + billing.",
  },
  {
    id: "sow-30.3-upi",
    source: "sow",
    citation: "SOW §30.3",
    title: "SEI monthly UPI summaries, employment data, strategies",
    status: "encoded",
    service_codes: ["SEI"],
    catalog_titles: [
      "SEI Monthly Summary — UPI Entry Attestation",
      "SEI Employment Data — UPI Entry Attestation",
      "SEI Employment Support Strategies — UPI Entry",
    ],
    note: "Typed into UPI by the 15th (or 14 days after PCSP update for strategies). Staff never touch UPI.",
  },
  {
    id: "sow-30.5",
    source: "sow",
    citation: "SOW §30.5",
    title: "SEI SSI / benefits knowledge",
    status: "encoded",
    service_codes: ["SEI"],
    catalog_titles: ["SEI — SSI/Benefits Knowledge Attestation"],
  },
  {
    id: "sow-30.6",
    source: "sow",
    citation: "SOW §30.6",
    title: "SEI USOR vendor + ACRE / USU Workplace Supports",
    status: "encoded",
    service_codes: ["SEI"],
    catalog_titles: [
      "USOR Approved Vendor — Job Coaching (SEI)",
      "ACRE Training Certification — SEI",
    ],
    audit_item_ids: ["IV-2", "IV-USOR"],
    note: "Existing SEI providers have until January 31, 2027 for USOR vendor proof.",
  },
  {
    id: "sow-30.7",
    source: "sow",
    citation: "SOW §30.7",
    title: "SEI fiscal-year outcome report (Google Form, Aug 30)",
    status: "encoded",
    service_codes: ["SEI"],
    catalog_titles: ["SEI Annual Outcome Report — Google Form Submission"],
  },
  {
    id: "sow-31-slh-delivery",
    source: "sow",
    citation: "SOW Article 31.1–31.4",
    title: "SLH delivery, belongings, sleep-time unbillable",
    status: "live_artifact",
    service_codes: ["SLH"],
    audit_item_ids: ["II-9", "III-2", "III-3"],
    note: "Belongings inventory is live. Asleep time is unbillable. EVV applies to SLH.",
  },
  {
    id: "sow-31.5",
    source: "sow",
    citation: "SOW §31.5",
    title: "SLH Supported Living outcome report (Google Form, Aug 30)",
    status: "encoded",
    service_codes: ["SLH"],
    catalog_titles: ["Supported Living Annual Outcome Report — Google Form Submission"],
    note: "Shared form with SLN §32.7.",
  },
  {
    id: "sow-32-sln-delivery",
    source: "sow",
    citation: "SOW Article 32.1–32.4 / 32.6",
    title: "SLN / CMP / CMS delivery and hour caps",
    status: "live_artifact",
    service_codes: ["SLN", "CMP", "CMS"],
    audit_item_ids: ["III-2", "III-3"],
    note: "CMP/CMS max 8h/day and 40h/wk are billing constraints. EVV applies.",
  },
  {
    id: "sow-32.3",
    source: "sow",
    citation: "SOW §32.3",
    title: "CMP/CMS monthly summaries to the Support Coordinator",
    status: "encoded",
    service_codes: ["CMP", "CMS"],
    catalog_titles: ["CMP/CMS Monthly Summaries — Submitted to SC"],
    note: "Due the 15th of the following month. TNS may not be awarded CMP/CMS; the row hides without those codes.",
  },
  {
    id: "sow-32.5",
    source: "sow",
    citation: "SOW §32.5",
    title: "DSPD New Caregiver Compensation training (CMP/CMS)",
    status: "encoded",
    service_codes: ["CMP", "CMS"],
    catalog_titles: ["DSPD New Caregiver Compensation Training — CMP/CMS"],
  },
  {
    id: "sow-32.7",
    source: "sow",
    citation: "SOW §32.7",
    title: "SLN Supported Living outcome report (Google Form, Aug 30)",
    status: "encoded",
    service_codes: ["SLN"],
    catalog_titles: ["Supported Living Annual Outcome Report — Google Form Submission"],
    note: "Shared form with SLH §31.5.",
  },

  // ── Other code articles already in the catalog (not TNS-primary) ────────
  {
    id: "sow-7.5",
    source: "sow",
    citation: "SOW §7.5",
    title: "DSG/DSP OL Day Treatment / Day Support",
    status: "encoded",
    service_codes: ["DSG", "DSP"],
    catalog_titles: [
      "OL Day Treatment License — 4+ Persons",
      "OL Day Support Certification — 3 or Fewer Persons",
    ],
    audit_item_ids: ["I-1-DSG"],
    note: "Hidden unless the org is awarded DSG/DSP.",
  },
  {
    id: "sow-9-epr",
    source: "sow",
    citation: "SOW Article 9",
    title: "EPR 20% community time + employment goals",
    status: "live_artifact",
    service_codes: ["EPR"],
    audit_item_ids: ["I-6", "II-5"],
    note: "Review-tool row only. Not seeded as a second to-do.",
  },
  {
    id: "sow-12-hsq",
    source: "sow",
    citation: "SOW Article 12",
    title: "HSQ clean/sanitary/safe environment training",
    status: "encoded",
    service_codes: ["HSQ"],
    catalog_titles: ["HSQ — Clean, Sanitary & Safe Environment Training"],
  },
  {
    id: "sow-15-pba",
    source: "sow",
    citation: "SOW Article 15 / §1.28",
    title: "PBA monthly financials",
    status: "live_artifact",
    service_codes: ["PBA"],
    audit_item_ids: ["II-PBA"],
    note: "Only if the program is the PBA / representative payee.",
  },
  {
    id: "sow-20-pps",
    source: "sow",
    citation: "SOW Article 20",
    title: "PPS foster-care license, drills, room-and-board",
    status: "encoded",
    service_codes: ["PPS"],
    catalog_titles: [
      "Child Placing / Foster Care License (DHHS/OL) — PPS",
      "PPS Quarterly Evacuation Drills — All Sites",
    ],
    audit_item_ids: ["I-2-PPS", "II-10-PPS"],
    note: "Belongings / room-and-board are live Person artifacts.",
  },
  {
    id: "sow-21-rhs",
    source: "sow",
    citation: "SOW Article 21",
    title: "RHS OL license/cert, drills, lease",
    status: "encoded",
    service_codes: ["RHS"],
    catalog_titles: [
      "OL Residential Support License — 4+ Persons per Site",
      "OL Residential Support Certification — 3 or Fewer Persons per Site",
      "RHS Quarterly Evacuation Drills — All Sites",
    ],
    audit_item_ids: ["I-1-RHS", "II-10-RHS"],
  },
  {
    id: "sow-28-sed",
    source: "sow",
    citation: "SOW §28.4",
    title: "SED ACRE training",
    status: "encoded",
    service_codes: ["SED"],
    catalog_titles: ["ACRE Training Certification — SED"],
  },
  {
    id: "sow-29-see",
    source: "sow",
    citation: "SOW §29.4",
    title: "SEE USU Customized Employment training",
    status: "encoded",
    service_codes: ["SEE", "SJD"],
    catalog_titles: ["Customized Employment Training (USU) — SEE/SJD"],
  },
  {
    id: "sow-33-sjd",
    source: "sow",
    citation: "SOW Article 33",
    title: "SJD UPI summaries, USOR contact, vendor, ACRE",
    status: "encoded",
    service_codes: ["SJD"],
    catalog_titles: [
      "SJD Monthly Summary — UPI Entry Attestation",
      "SJD Employment Data — UPI Entry Attestation",
      "SJD Monthly USOR Contact Verification",
      "USOR Approved Vendor — Job Development (SJD)",
      "ACRE Training Certification — SJD (60 Days)",
    ],
  },
  {
    id: "sow-3-5-bc",
    source: "sow",
    citation: "SOW Articles 3–5",
    title: "Behavior consultation FBA / BSP",
    status: "live_artifact",
    service_codes: ["BC1", "BC2", "BC3"],
    audit_item_ids: ["II-4"],
    note: "Behavior-support module. Hidden unless BC codes are awarded.",
  },
  {
    id: "sow-other-codes",
    source: "sow",
    citation: "SOW Articles 6, 10, 13–14, 16–19, 22–27, 34–36",
    title: "Other service-code articles (COM, ELS, MTP, PAC, nursing, respite, SEC, SJP, SJR, TFB)",
    status: "intentional_omit",
    note: "Delivery and billing constraints for codes this pack does not seed as extra register rows. If an org is awarded one, HIVE still applies EVV / unit math / timesheet rules. New contractor-file duties for those codes are a pack revision, not a tenant edit.",
  },

  // ── Client Service Terms on the review tool ─────────────────────────────
  {
    id: "cst-46-plan",
    source: "cst",
    citation: "CST 46",
    title: "Emergency Management and Business Continuity Plan",
    status: "encoded",
    catalog_titles: ["Emergency Management and Business Continuity Plan"],
    audit_item_ids: ["I-4"],
  },
  {
    id: "cst-46-training",
    source: "cst",
    citation: "CST 46",
    title: "Annual Emergency Management Plan training",
    status: "encoded",
    catalog_titles: ["Annual Emergency Management Plan Training"],
    audit_item_ids: ["IV-4"],
  },
  {
    id: "cst-9-10",
    source: "cst",
    citation: "CST 9 & 10",
    title: "Staff conflict of interest process",
    status: "encoded",
    catalog_titles: ["Staff Conflict of Interest Process"],
    audit_item_ids: ["I-8"],
  },
  {
    id: "cst-50",
    source: "cst",
    citation: "CST 50",
    title: "Internal Quality Management Plan",
    status: "encoded",
    catalog_titles: ["Internal Quality Management Plan"],
    audit_item_ids: ["I-10"],
  },
  {
    id: "cst-29-36",
    source: "cst",
    citation: "CST 29–36",
    title: "General, Professional, and Automobile liability insurance",
    status: "encoded",
    catalog_titles: ["General, Professional, and Automobile Liability Insurance"],
    audit_item_ids: ["I-12"],
  },
  {
    id: "cst-76",
    source: "cst",
    citation: "CST 76",
    title: "DHHS Code of Conduct signed (SLN/SLH/HHS/PPS)",
    status: "encoded",
    catalog_titles: ["DHHS Code of Conduct — Signed"],
    audit_item_ids: ["IV-COC"],
    service_codes: ["SLN", "SLH", "HHS", "PPS"],
  },
  {
    id: "cst-55-56",
    source: "cst",
    citation: "CST 55 & 56",
    title: "Timesheet / attendance content",
    status: "live_artifact",
    audit_item_ids: ["III-1"],
    note: "Same live timesheet artifact as SOW §1.10(7).",
  },
  {
    id: "cst-72",
    source: "cst",
    citation: "CST 72",
    title: "Background screening (CST restatement)",
    status: "encoded",
    catalog_titles: ["Background Screening — Annual"],
    audit_item_ids: ["IV-BG"],
    note: "Same duty as SOW §1.9(2).",
  },

  // ── Review-tool rows (every numbered item) ──────────────────────────────
  {
    id: "rt-I-1-DSI",
    source: "review_tool",
    citation: "Review tool I-1 (DSI)",
    title: "OL Day Treatment / Day Support for DSI",
    status: "encoded",
    audit_item_ids: ["I-1-DSI"],
    catalog_titles: [
      "OL Day Treatment License — 4+ Persons",
      "OL Day Support Certification — 3 or Fewer Persons",
    ],
    note: "Paper tool Part I item 1, split by service.",
  },
  {
    id: "rt-I-1-DSG",
    source: "review_tool",
    citation: "Review tool I-1 (DSG/DSP)",
    title: "OL Day Treatment / Day Support for DSG/DSP",
    status: "encoded",
    audit_item_ids: ["I-1-DSG"],
    catalog_titles: [
      "OL Day Treatment License — 4+ Persons",
      "OL Day Support Certification — 3 or Fewer Persons",
    ],
    note: "Hidden unless DSG/DSP is awarded.",
  },
  {
    id: "rt-I-1-RHS",
    source: "review_tool",
    citation: "Review tool I-1 (RHS)",
    title: "OL Residential Support license/cert",
    status: "encoded",
    audit_item_ids: ["I-1-RHS"],
    catalog_titles: [
      "OL Residential Support License — 4+ Persons per Site",
      "OL Residential Support Certification — 3 or Fewer Persons per Site",
    ],
  },
  {
    id: "rt-I-2-HHS",
    source: "review_tool",
    citation: "Review tool I-2 (HHS)",
    title: "Host Home Certification",
    status: "encoded",
    audit_item_ids: ["I-2-HHS"],
    catalog_titles: ["HHS Home Certification — Annual (DSPD Form)"],
  },
  {
    id: "rt-I-2-PPS",
    source: "review_tool",
    citation: "Review tool I-2 (PPS)",
    title: "Child Placing / Foster Care license",
    status: "encoded",
    audit_item_ids: ["I-2-PPS"],
    catalog_titles: ["Child Placing / Foster Care License (DHHS/OL) — PPS"],
  },
  {
    id: "rt-I-3",
    source: "review_tool",
    citation: "Review tool I-3",
    title: "Human Rights Committee established and meeting",
    status: "live_artifact",
    audit_item_ids: ["I-3"],
    note: "HRC module. Written Human Rights Plan is the separate §1.21 duty.",
  },
  {
    id: "rt-I-4",
    source: "review_tool",
    citation: "Review tool I-4",
    title: "Emergency Management Plan current",
    status: "encoded",
    audit_item_ids: ["I-4"],
    catalog_titles: ["Emergency Management and Business Continuity Plan"],
  },
  {
    id: "rt-I-5",
    source: "review_tool",
    citation: "Review tool I-5",
    title: "Incident reporting process / UPI timelines",
    status: "live_artifact",
    audit_item_ids: ["I-5"],
  },
  {
    id: "rt-I-6",
    source: "review_tool",
    citation: "Review tool I-6",
    title: "EPR 20% community time",
    status: "live_artifact",
    audit_item_ids: ["I-6"],
  },
  {
    id: "rt-I-7",
    source: "review_tool",
    citation: "Review tool I-7",
    title: "No gifts / purchases-from-staff process",
    status: "encoded",
    audit_item_ids: ["I-7"],
    catalog_titles: ["No Gifts or Purchases-from-Staff Process"],
  },
  {
    id: "rt-I-8",
    source: "review_tool",
    citation: "Review tool I-8",
    title: "Staff conflict of interest process",
    status: "encoded",
    audit_item_ids: ["I-8"],
    catalog_titles: ["Staff Conflict of Interest Process"],
  },
  {
    id: "rt-I-9",
    source: "review_tool",
    citation: "Review tool I-9",
    title: "Person discharge process",
    status: "encoded",
    audit_item_ids: ["I-9"],
    catalog_titles: ["Person Discharge Process"],
  },
  {
    id: "rt-I-10",
    source: "review_tool",
    citation: "Review tool I-10",
    title: "Internal Quality Management Plan",
    status: "encoded",
    audit_item_ids: ["I-10"],
    catalog_titles: ["Internal Quality Management Plan"],
  },
  {
    id: "rt-I-11",
    source: "review_tool",
    citation: "Review tool I-11",
    title: "Loans of $2,000+ disclosed to DHHS QA",
    status: "live_artifact",
    audit_item_ids: ["I-11"],
  },
  {
    id: "rt-I-12",
    source: "review_tool",
    citation: "Review tool I-12",
    title: "Liability insurance at contracted minimums",
    status: "encoded",
    audit_item_ids: ["I-12"],
    catalog_titles: ["General, Professional, and Automobile Liability Insurance"],
  },
  {
    id: "rt-II-1",
    source: "review_tool",
    citation: "Review tool II-1",
    title: "Medical and dental examinations",
    status: "live_artifact",
    audit_item_ids: ["II-1"],
  },
  {
    id: "rt-II-2",
    source: "review_tool",
    citation: "Review tool II-2",
    title: "Medication record when contractor supports meds",
    status: "live_artifact",
    audit_item_ids: ["II-2"],
  },
  {
    id: "rt-II-3",
    source: "review_tool",
    citation: "Review tool II-3",
    title: "Support Strategies for PCSP goals",
    status: "encoded",
    audit_item_ids: ["II-3"],
    catalog_titles: ["Support Strategies — [Client Name]"],
  },
  {
    id: "rt-II-4",
    source: "review_tool",
    citation: "Review tool II-4",
    title: "FBA and BSP for BC1/BC2/BC3",
    status: "live_artifact",
    audit_item_ids: ["II-4"],
  },
  {
    id: "rt-II-5",
    source: "review_tool",
    citation: "Review tool II-5",
    title: "Employment supports follow CIE goals",
    status: "encoded",
    audit_item_ids: ["II-5"],
    catalog_titles: [
      "SEI Employment Data — UPI Entry Attestation",
      "SEI Employment Support Strategies — UPI Entry",
      "SEI — SSI/Benefits Knowledge Attestation",
    ],
  },
  {
    id: "rt-II-6",
    source: "review_tool",
    citation: "Review tool II-6",
    title: "Quarterly / monthly summaries",
    status: "live_artifact",
    audit_item_ids: ["II-6"],
    catalog_titles: [
      "SEI Monthly Summary — UPI Entry Attestation",
      "CMP/CMS Monthly Summaries — Submitted to SC",
      "SJD Monthly Summary — UPI Entry Attestation",
    ],
  },
  {
    id: "rt-II-7",
    source: "review_tool",
    citation: "Review tool II-7",
    title: "Signed grievance-policy acknowledgment",
    status: "live_artifact",
    audit_item_ids: ["II-7"],
  },
  {
    id: "rt-II-8",
    source: "review_tool",
    citation: "Review tool II-8",
    title: "Human-rights restriction documentation (a–h)",
    status: "live_artifact",
    audit_item_ids: ["II-8"],
  },
  {
    id: "rt-II-9",
    source: "review_tool",
    citation: "Review tool II-9",
    title: "Belongings inventory (annual, $50+)",
    status: "live_artifact",
    audit_item_ids: ["II-9"],
  },
  {
    id: "rt-II-10-HHS",
    source: "review_tool",
    citation: "Review tool II-10 (HHS)",
    title: "HHS room-and-board agreement",
    status: "live_artifact",
    audit_item_ids: ["II-10-HHS"],
  },
  {
    id: "rt-II-10-RHS",
    source: "review_tool",
    citation: "Review tool II-10 (RHS)",
    title: "RHS lease agreement",
    status: "live_artifact",
    audit_item_ids: ["II-10-RHS"],
  },
  {
    id: "rt-II-10-PPS",
    source: "review_tool",
    citation: "Review tool II-10 (PPS)",
    title: "PPS room-and-board agreement",
    status: "live_artifact",
    audit_item_ids: ["II-10-PPS"],
  },
  {
    id: "rt-II-PBA",
    source: "review_tool",
    citation: "Review tool II-PBA",
    title: "PBA / representative-payee financial review",
    status: "live_artifact",
    audit_item_ids: ["II-PBA"],
  },
  {
    id: "rt-II-LOAN",
    source: "review_tool",
    citation: "Review tool II-Loans",
    title: "Emergency loan documentation",
    status: "live_artifact",
    audit_item_ids: ["II-LOAN"],
  },
  {
    id: "rt-III-1",
    source: "review_tool",
    citation: "Review tool III-1",
    title: "Accurate attendance / timesheets",
    status: "live_artifact",
    audit_item_ids: ["III-1"],
  },
  {
    id: "rt-III-2",
    source: "review_tool",
    citation: "Review tool III-2",
    title: "Electronic Visit Verification",
    status: "live_artifact",
    audit_item_ids: ["III-2"],
  },
  {
    id: "rt-III-3",
    source: "review_tool",
    citation: "Review tool III-3",
    title: "Billed services match the service-code description",
    status: "live_artifact",
    audit_item_ids: ["III-3"],
  },
  {
    id: "rt-III-HHS",
    source: "review_tool",
    citation: "Review tool III-HHS",
    title: "Billable HHS day = Present + daily note",
    status: "live_artifact",
    audit_item_ids: ["III-HHS"],
  },
  {
    id: "rt-IV-BG",
    source: "review_tool",
    citation: "Review tool IV-BG",
    title: "Annual background screening",
    status: "encoded",
    audit_item_ids: ["IV-BG"],
    catalog_titles: ["Background Screening — Annual"],
  },
  {
    id: "rt-IV-COC",
    source: "review_tool",
    citation: "Review tool IV-CoC",
    title: "DHHS Code of Conduct signed",
    status: "encoded",
    audit_item_ids: ["IV-COC"],
    catalog_titles: ["DHHS Code of Conduct — Signed"],
  },
  {
    id: "rt-IV-1",
    source: "review_tool",
    citation: "Review tool IV-1",
    title: "BCBA / RN / LPN credentials",
    status: "encoded",
    audit_item_ids: ["IV-1"],
    catalog_titles: ["Educational Credentials and Licenses — On File"],
  },
  {
    id: "rt-IV-2",
    source: "review_tool",
    citation: "Review tool IV-2",
    title: "ACRE / USU Workplace Supports for SEI",
    status: "encoded",
    audit_item_ids: ["IV-2"],
    catalog_titles: [
      "ACRE Training Certification — SEI",
      "ACRE Training Certification — SED",
      "Customized Employment Training (USU) — SEE/SJD",
    ],
  },
  {
    id: "rt-IV-3",
    source: "review_tool",
    citation: "Review tool IV-3",
    title: "OIG exclusion check",
    status: "encoded",
    audit_item_ids: ["IV-3"],
    catalog_titles: ["Medicaid Fraud & Abuse Exclusion Screening — Annual"],
  },
  {
    id: "rt-IV-4",
    source: "review_tool",
    citation: "Review tool IV-4",
    title: "Annual Emergency Management Plan training",
    status: "encoded",
    audit_item_ids: ["IV-4"],
    catalog_titles: ["Annual Emergency Management Plan Training"],
  },
  {
    id: "rt-IV-5",
    source: "review_tool",
    citation: "Review tool IV-5",
    title: "Verifiable training file per staff",
    status: "encoded",
    audit_item_ids: ["IV-5"],
    catalog_titles: ["Training Documentation File — Maintained"],
  },
  {
    id: "rt-IV-6",
    source: "review_tool",
    citation: "Review tool IV-6",
    title: "30-day orientation A–W",
    status: "encoded",
    audit_item_ids: ["IV-6"],
    catalog_titles: [
      "30-Day New Hire Orientation Training",
      "Client-Specific Training — [Client Name]",
    ],
  },
  {
    id: "rt-IV-7",
    source: "review_tool",
    citation: "Review tool IV-7",
    title: "90-day CPR / First Aid / person-centered thinking",
    status: "encoded",
    audit_item_ids: ["IV-7"],
    catalog_titles: [
      "CPR/First Aid Certification — Initial",
      "CPR/First Aid Certification — Renewal",
      "Person-Centered Thinking and Practices Training",
    ],
  },
  {
    id: "rt-IV-8",
    source: "review_tool",
    citation: "Review tool IV-8",
    title: "Behavior-intervention certification",
    status: "encoded",
    audit_item_ids: ["IV-8"],
    catalog_titles: ["Behavior Intervention Certification (SOAR/MANDT/PART/CPI/Safety Care)"],
  },
  {
    id: "rt-IV-9",
    source: "review_tool",
    citation: "Review tool IV-9",
    title: "12-hour annual CE from year two",
    status: "encoded",
    audit_item_ids: ["IV-9"],
    catalog_titles: ["Annual 12-Hour Continuing Education"],
  },
  {
    id: "rt-IV-10",
    source: "review_tool",
    citation: "Review tool IV-10",
    title: "ABI training before working alone",
    status: "encoded",
    audit_item_ids: ["IV-10"],
    catalog_titles: ["ABI Training — Before Working Alone"],
  },
  {
    id: "rt-IV-USOR",
    source: "review_tool",
    citation: "Review tool IV-SEI-Q",
    title: "USOR vendor + SEI staff qualifications",
    status: "encoded",
    audit_item_ids: ["IV-USOR"],
    catalog_titles: [
      "USOR Approved Vendor — Job Coaching (SEI)",
      "ACRE Training Certification — SEI",
    ],
  },
];
